// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockSalesPhaseSearcher is an autogenerated mock type for the SalesPhaseSearcher type
type MockSalesPhaseSearcher struct {
	mock.Mock
}

type MockSalesPhaseSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalesPhaseSearcher) EXPECT() *MockSalesPhaseSearcher_Expecter {
	return &MockSalesPhaseSearcher_Expecter{mock: &_m.Mock}
}

// SearchSalesPhases provides a mock function with given fields: ctx, in
func (_m *MockSalesPhaseSearcher) SearchSalesPhases(ctx context.Context, in *entity.SalesPhaseSearchInput) ([]*entity.SalesPhaseCandidate, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SearchSalesPhases")
	}

	var r0 []*entity.SalesPhaseCandidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SalesPhaseSearchInput) ([]*entity.SalesPhaseCandidate, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SalesPhaseSearchInput) []*entity.SalesPhaseCandidate); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SalesPhaseCandidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SalesPhaseSearchInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSalesPhaseSearcher_SearchSalesPhases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSalesPhases'
type MockSalesPhaseSearcher_SearchSalesPhases_Call struct {
	*mock.Call
}

// SearchSalesPhases is a helper method to define mock.On call
//   - ctx context.Context
//   - in *entity.SalesPhaseSearchInput
func (_e *MockSalesPhaseSearcher_Expecter) SearchSalesPhases(ctx interface{}, in interface{}) *MockSalesPhaseSearcher_SearchSalesPhases_Call {
	return &MockSalesPhaseSearcher_SearchSalesPhases_Call{Call: _e.mock.On("SearchSalesPhases", ctx, in)}
}

func (_c *MockSalesPhaseSearcher_SearchSalesPhases_Call) Run(run func(ctx context.Context, in *entity.SalesPhaseSearchInput)) *MockSalesPhaseSearcher_SearchSalesPhases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SalesPhaseSearchInput))
	})
	return _c
}

func (_c *MockSalesPhaseSearcher_SearchSalesPhases_Call) Return(_a0 []*entity.SalesPhaseCandidate, _a1 error) *MockSalesPhaseSearcher_SearchSalesPhases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSalesPhaseSearcher_SearchSalesPhases_Call) RunAndReturn(run func(context.Context, *entity.SalesPhaseSearchInput) ([]*entity.SalesPhaseCandidate, error)) *MockSalesPhaseSearcher_SearchSalesPhases_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalesPhaseSearcher creates a new instance of MockSalesPhaseSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalesPhaseSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalesPhaseSearcher {
	mock := &MockSalesPhaseSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
