// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentCapturePort is an autogenerated mock type for the PaymentCapturePort type
type MockPaymentCapturePort struct {
	mock.Mock
}

type MockPaymentCapturePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentCapturePort) EXPECT() *MockPaymentCapturePort_Expecter {
	return &MockPaymentCapturePort_Expecter{mock: &_m.Mock}
}

// GetCapturedPayment provides a mock function with given fields: ctx, paymentIntentRef
func (_m *MockPaymentCapturePort) GetCapturedPayment(ctx context.Context, paymentIntentRef string) (*entity.CapturedPayment, error) {
	ret := _m.Called(ctx, paymentIntentRef)

	if len(ret) == 0 {
		panic("no return value specified for GetCapturedPayment")
	}

	var r0 *entity.CapturedPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.CapturedPayment, error)); ok {
		return rf(ctx, paymentIntentRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.CapturedPayment); ok {
		r0 = rf(ctx, paymentIntentRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CapturedPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentIntentRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCapturePort_GetCapturedPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapturedPayment'
type MockPaymentCapturePort_GetCapturedPayment_Call struct {
	*mock.Call
}

// GetCapturedPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentRef string
func (_e *MockPaymentCapturePort_Expecter) GetCapturedPayment(ctx interface{}, paymentIntentRef interface{}) *MockPaymentCapturePort_GetCapturedPayment_Call {
	return &MockPaymentCapturePort_GetCapturedPayment_Call{Call: _e.mock.On("GetCapturedPayment", ctx, paymentIntentRef)}
}

func (_c *MockPaymentCapturePort_GetCapturedPayment_Call) Run(run func(ctx context.Context, paymentIntentRef string)) *MockPaymentCapturePort_GetCapturedPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentCapturePort_GetCapturedPayment_Call) Return(_a0 *entity.CapturedPayment, _a1 error) *MockPaymentCapturePort_GetCapturedPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCapturePort_GetCapturedPayment_Call) RunAndReturn(run func(context.Context, string) (*entity.CapturedPayment, error)) *MockPaymentCapturePort_GetCapturedPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentCapturePort creates a new instance of MockPaymentCapturePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentCapturePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentCapturePort {
	mock := &MockPaymentCapturePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
