// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaProcessor is an autogenerated mock type for the MediaProcessor type
type MockMediaProcessor struct {
	mock.Mock
}

type MockMediaProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaProcessor) EXPECT() *MockMediaProcessor_Expecter {
	return &MockMediaProcessor_Expecter{mock: &_m.Mock}
}

// ProcessImage provides a mock function with given fields: ctx, data
func (_m *MockMediaProcessor) ProcessImage(ctx context.Context, data []byte) ([]byte, []byte, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ProcessImage")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, []byte, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) []byte); ok {
		r1 = rf(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []byte) error); ok {
		r2 = rf(ctx, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMediaProcessor_ProcessImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessImage'
type MockMediaProcessor_ProcessImage_Call struct {
	*mock.Call
}

// ProcessImage is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockMediaProcessor_Expecter) ProcessImage(ctx interface{}, data interface{}) *MockMediaProcessor_ProcessImage_Call {
	return &MockMediaProcessor_ProcessImage_Call{Call: _e.mock.On("ProcessImage", ctx, data)}
}

func (_c *MockMediaProcessor_ProcessImage_Call) Run(run func(ctx context.Context, data []byte)) *MockMediaProcessor_ProcessImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockMediaProcessor_ProcessImage_Call) Return(thumb []byte, large []byte, err error) *MockMediaProcessor_ProcessImage_Call {
	_c.Call.Return(thumb, large, err)
	return _c
}

func (_c *MockMediaProcessor_ProcessImage_Call) RunAndReturn(run func(context.Context, []byte) ([]byte, []byte, error)) *MockMediaProcessor_ProcessImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaProcessor creates a new instance of MockMediaProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaProcessor {
	mock := &MockMediaProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
