// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockArtistRepository creates a new instance of MockArtistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistRepository {
	mock := &MockArtistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtistRepository is an autogenerated mock type for the ArtistRepository type
type MockArtistRepository struct {
	mock.Mock
}

type MockArtistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistRepository) EXPECT() *MockArtistRepository_Expecter {
	return &MockArtistRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) Create(ctx context.Context, artist *entity.Artist) error {
	ret := _mock.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Artist) error); ok {
		r0 = returnFunc(ctx, artist)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArtistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
func (_e *MockArtistRepository_Expecter) Create(ctx interface{}, artist interface{}) *MockArtistRepository_Create_Call {
	return &MockArtistRepository_Create_Call{Call: _e.mock.On("Create", ctx, artist)}
}

func (_c *MockArtistRepository_Create_Call) Run(run func(ctx context.Context, artist *entity.Artist)) *MockArtistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Artist
		if args[1] != nil {
			arg1 = args[1].(*entity.Artist)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_Create_Call) Return(err error) *MockArtistRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_Create_Call) RunAndReturn(run func(ctx context.Context, artist *entity.Artist) error) *MockArtistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOfficialSite provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) CreateOfficialSite(ctx context.Context, site *entity.OfficialSite) error {
	ret := _mock.Called(ctx, site)

	if len(ret) == 0 {
		panic("no return value specified for CreateOfficialSite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OfficialSite) error); ok {
		r0 = returnFunc(ctx, site)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_CreateOfficialSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOfficialSite'
type MockArtistRepository_CreateOfficialSite_Call struct {
	*mock.Call
}

// CreateOfficialSite is a helper method to define mock.On call
//   - ctx context.Context
//   - site *entity.OfficialSite
func (_e *MockArtistRepository_Expecter) CreateOfficialSite(ctx interface{}, site interface{}) *MockArtistRepository_CreateOfficialSite_Call {
	return &MockArtistRepository_CreateOfficialSite_Call{Call: _e.mock.On("CreateOfficialSite", ctx, site)}
}

func (_c *MockArtistRepository_CreateOfficialSite_Call) Run(run func(ctx context.Context, site *entity.OfficialSite)) *MockArtistRepository_CreateOfficialSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.OfficialSite
		if args[1] != nil {
			arg1 = args[1].(*entity.OfficialSite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_CreateOfficialSite_Call) Return(err error) *MockArtistRepository_CreateOfficialSite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_CreateOfficialSite_Call) RunAndReturn(run func(ctx context.Context, site *entity.OfficialSite) error) *MockArtistRepository_CreateOfficialSite_Call {
	_c.Call.Return(run)
	return _c
}

// Follow provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) Follow(ctx context.Context, userID string, artistID string) error {
	ret := _mock.Called(ctx, userID, artistID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, artistID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockArtistRepository_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - artistID string
func (_e *MockArtistRepository_Expecter) Follow(ctx interface{}, userID interface{}, artistID interface{}) *MockArtistRepository_Follow_Call {
	return &MockArtistRepository_Follow_Call{Call: _e.mock.On("Follow", ctx, userID, artistID)}
}

func (_c *MockArtistRepository_Follow_Call) Run(run func(ctx context.Context, userID string, artistID string)) *MockArtistRepository_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtistRepository_Follow_Call) Return(err error) *MockArtistRepository_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_Follow_Call) RunAndReturn(run func(ctx context.Context, userID string, artistID string) error) *MockArtistRepository_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) Get(ctx context.Context, id string) (*entity.Artist, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Artist, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Artist); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockArtistRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockArtistRepository_Expecter) Get(ctx interface{}, id interface{}) *MockArtistRepository_Get_Call {
	return &MockArtistRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockArtistRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockArtistRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_Get_Call) Return(artist *entity.Artist, err error) *MockArtistRepository_Get_Call {
	_c.Call.Return(artist, err)
	return _c
}

func (_c *MockArtistRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Artist, error)) *MockArtistRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMBID provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) GetByMBID(ctx context.Context, mbid string) (*entity.Artist, error) {
	ret := _mock.Called(ctx, mbid)

	if len(ret) == 0 {
		panic("no return value specified for GetByMBID")
	}

	var r0 *entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Artist, error)); ok {
		return returnFunc(ctx, mbid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Artist); ok {
		r0 = returnFunc(ctx, mbid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mbid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_GetByMBID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMBID'
type MockArtistRepository_GetByMBID_Call struct {
	*mock.Call
}

// GetByMBID is a helper method to define mock.On call
//   - ctx context.Context
//   - mbid string
func (_e *MockArtistRepository_Expecter) GetByMBID(ctx interface{}, mbid interface{}) *MockArtistRepository_GetByMBID_Call {
	return &MockArtistRepository_GetByMBID_Call{Call: _e.mock.On("GetByMBID", ctx, mbid)}
}

func (_c *MockArtistRepository_GetByMBID_Call) Run(run func(ctx context.Context, mbid string)) *MockArtistRepository_GetByMBID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_GetByMBID_Call) Return(artist *entity.Artist, err error) *MockArtistRepository_GetByMBID_Call {
	_c.Call.Return(artist, err)
	return _c
}

func (_c *MockArtistRepository_GetByMBID_Call) RunAndReturn(run func(ctx context.Context, mbid string) (*entity.Artist, error)) *MockArtistRepository_GetByMBID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfficialSite provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) GetOfficialSite(ctx context.Context, artistID string) (*entity.OfficialSite, error) {
	ret := _mock.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficialSite")
	}

	var r0 *entity.OfficialSite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.OfficialSite, error)); ok {
		return returnFunc(ctx, artistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.OfficialSite); ok {
		r0 = returnFunc(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OfficialSite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_GetOfficialSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfficialSite'
type MockArtistRepository_GetOfficialSite_Call struct {
	*mock.Call
}

// GetOfficialSite is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockArtistRepository_Expecter) GetOfficialSite(ctx interface{}, artistID interface{}) *MockArtistRepository_GetOfficialSite_Call {
	return &MockArtistRepository_GetOfficialSite_Call{Call: _e.mock.On("GetOfficialSite", ctx, artistID)}
}

func (_c *MockArtistRepository_GetOfficialSite_Call) Run(run func(ctx context.Context, artistID string)) *MockArtistRepository_GetOfficialSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_GetOfficialSite_Call) Return(officialSite *entity.OfficialSite, err error) *MockArtistRepository_GetOfficialSite_Call {
	_c.Call.Return(officialSite, err)
	return _c
}

func (_c *MockArtistRepository_GetOfficialSite_Call) RunAndReturn(run func(ctx context.Context, artistID string) (*entity.OfficialSite, error)) *MockArtistRepository_GetOfficialSite_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) List(ctx context.Context) ([]*entity.Artist, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Artist, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Artist); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockArtistRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockArtistRepository_Expecter) List(ctx interface{}) *MockArtistRepository_List_Call {
	return &MockArtistRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockArtistRepository_List_Call) Run(run func(ctx context.Context)) *MockArtistRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArtistRepository_List_Call) Return(artists []*entity.Artist, err error) *MockArtistRepository_List_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Artist, error)) *MockArtistRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFollowed provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) ListFollowed(ctx context.Context, userID string) ([]*entity.Artist, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFollowed")
	}

	var r0 []*entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Artist, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Artist); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_ListFollowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFollowed'
type MockArtistRepository_ListFollowed_Call struct {
	*mock.Call
}

// ListFollowed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockArtistRepository_Expecter) ListFollowed(ctx interface{}, userID interface{}) *MockArtistRepository_ListFollowed_Call {
	return &MockArtistRepository_ListFollowed_Call{Call: _e.mock.On("ListFollowed", ctx, userID)}
}

func (_c *MockArtistRepository_ListFollowed_Call) Run(run func(ctx context.Context, userID string)) *MockArtistRepository_ListFollowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_ListFollowed_Call) Return(artists []*entity.Artist, err error) *MockArtistRepository_ListFollowed_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistRepository_ListFollowed_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Artist, error)) *MockArtistRepository_ListFollowed_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) Unfollow(ctx context.Context, userID string, artistID string) error {
	ret := _mock.Called(ctx, userID, artistID)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, artistID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockArtistRepository_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - artistID string
func (_e *MockArtistRepository_Expecter) Unfollow(ctx interface{}, userID interface{}, artistID interface{}) *MockArtistRepository_Unfollow_Call {
	return &MockArtistRepository_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, userID, artistID)}
}

func (_c *MockArtistRepository_Unfollow_Call) Run(run func(ctx context.Context, userID string, artistID string)) *MockArtistRepository_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtistRepository_Unfollow_Call) Return(err error) *MockArtistRepository_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_Unfollow_Call) RunAndReturn(run func(ctx context.Context, userID string, artistID string) error) *MockArtistRepository_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}
