// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAdmissionRepository is an autogenerated mock type for the AdmissionRepository type
type MockAdmissionRepository struct {
	mock.Mock
}

type MockAdmissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdmissionRepository) EXPECT() *MockAdmissionRepository_Expecter {
	return &MockAdmissionRepository_Expecter{mock: &_m.Mock}
}

// GetByTicket provides a mock function with given fields: ctx, ticketID
func (_m *MockAdmissionRepository) GetByTicket(ctx context.Context, ticketID entity.TicketID) (*entity.Admission, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTicket")
	}

	var r0 *entity.Admission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketID) (*entity.Admission, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketID) *entity.Admission); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Admission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TicketID) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdmissionRepository_GetByTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTicket'
type MockAdmissionRepository_GetByTicket_Call struct {
	*mock.Call
}

// GetByTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID entity.TicketID
func (_e *MockAdmissionRepository_Expecter) GetByTicket(ctx interface{}, ticketID interface{}) *MockAdmissionRepository_GetByTicket_Call {
	return &MockAdmissionRepository_GetByTicket_Call{Call: _e.mock.On("GetByTicket", ctx, ticketID)}
}

func (_c *MockAdmissionRepository_GetByTicket_Call) Run(run func(ctx context.Context, ticketID entity.TicketID)) *MockAdmissionRepository_GetByTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TicketID))
	})
	return _c
}

func (_c *MockAdmissionRepository_GetByTicket_Call) Return(_a0 *entity.Admission, _a1 error) *MockAdmissionRepository_GetByTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdmissionRepository_GetByTicket_Call) RunAndReturn(run func(context.Context, entity.TicketID) (*entity.Admission, error)) *MockAdmissionRepository_GetByTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdmissionRepository creates a new instance of MockAdmissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdmissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdmissionRepository {
	mock := &MockAdmissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
