// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockLotteryPhaseRepository is an autogenerated mock type for the LotteryPhaseRepository type
type MockLotteryPhaseRepository struct {
	mock.Mock
}

type MockLotteryPhaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLotteryPhaseRepository) EXPECT() *MockLotteryPhaseRepository_Expecter {
	return &MockLotteryPhaseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, phase
func (_m *MockLotteryPhaseRepository) Create(ctx context.Context, phase *entity.LotterySalesPhase) (*entity.LotterySalesPhase, error) {
	ret := _m.Called(ctx, phase)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.LotterySalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LotterySalesPhase) (*entity.LotterySalesPhase, error)); ok {
		return rf(ctx, phase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LotterySalesPhase) *entity.LotterySalesPhase); ok {
		r0 = rf(ctx, phase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LotterySalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.LotterySalesPhase) error); ok {
		r1 = rf(ctx, phase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLotteryPhaseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLotteryPhaseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - phase *entity.LotterySalesPhase
func (_e *MockLotteryPhaseRepository_Expecter) Create(ctx interface{}, phase interface{}) *MockLotteryPhaseRepository_Create_Call {
	return &MockLotteryPhaseRepository_Create_Call{Call: _e.mock.On("Create", ctx, phase)}
}

func (_c *MockLotteryPhaseRepository_Create_Call) Run(run func(ctx context.Context, phase *entity.LotterySalesPhase)) *MockLotteryPhaseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.LotterySalesPhase))
	})
	return _c
}

func (_c *MockLotteryPhaseRepository_Create_Call) Return(_a0 *entity.LotterySalesPhase, _a1 error) *MockLotteryPhaseRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLotteryPhaseRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.LotterySalesPhase) (*entity.LotterySalesPhase, error)) *MockLotteryPhaseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockLotteryPhaseRepository) Get(ctx context.Context, id entity.LotteryPhaseID) (*entity.LotterySalesPhase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.LotterySalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.LotteryPhaseID) (*entity.LotterySalesPhase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.LotteryPhaseID) *entity.LotterySalesPhase); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LotterySalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.LotteryPhaseID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLotteryPhaseRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLotteryPhaseRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.LotteryPhaseID
func (_e *MockLotteryPhaseRepository_Expecter) Get(ctx interface{}, id interface{}) *MockLotteryPhaseRepository_Get_Call {
	return &MockLotteryPhaseRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockLotteryPhaseRepository_Get_Call) Run(run func(ctx context.Context, id entity.LotteryPhaseID)) *MockLotteryPhaseRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.LotteryPhaseID))
	})
	return _c
}

func (_c *MockLotteryPhaseRepository_Get_Call) Return(_a0 *entity.LotterySalesPhase, _a1 error) *MockLotteryPhaseRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLotteryPhaseRepository_Get_Call) RunAndReturn(run func(context.Context, entity.LotteryPhaseID) (*entity.LotterySalesPhase, error)) *MockLotteryPhaseRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListPhasesDueForDraw provides a mock function with given fields: ctx, now
func (_m *MockLotteryPhaseRepository) ListPhasesDueForDraw(ctx context.Context, now time.Time) ([]*entity.LotterySalesPhase, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ListPhasesDueForDraw")
	}

	var r0 []*entity.LotterySalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*entity.LotterySalesPhase, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*entity.LotterySalesPhase); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.LotterySalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLotteryPhaseRepository_ListPhasesDueForDraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPhasesDueForDraw'
type MockLotteryPhaseRepository_ListPhasesDueForDraw_Call struct {
	*mock.Call
}

// ListPhasesDueForDraw is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockLotteryPhaseRepository_Expecter) ListPhasesDueForDraw(ctx interface{}, now interface{}) *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call {
	return &MockLotteryPhaseRepository_ListPhasesDueForDraw_Call{Call: _e.mock.On("ListPhasesDueForDraw", ctx, now)}
}

func (_c *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call) Run(run func(ctx context.Context, now time.Time)) *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call) Return(_a0 []*entity.LotterySalesPhase, _a1 error) *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call) RunAndReturn(run func(context.Context, time.Time) ([]*entity.LotterySalesPhase, error)) *MockLotteryPhaseRepository_ListPhasesDueForDraw_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVerificationRequirement provides a mock function with given fields: ctx, id, req
func (_m *MockLotteryPhaseRepository) UpdateVerificationRequirement(ctx context.Context, id entity.LotteryPhaseID, req entity.VerificationRequirement) (*entity.LotterySalesPhase, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVerificationRequirement")
	}

	var r0 *entity.LotterySalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.LotteryPhaseID, entity.VerificationRequirement) (*entity.LotterySalesPhase, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.LotteryPhaseID, entity.VerificationRequirement) *entity.LotterySalesPhase); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LotterySalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.LotteryPhaseID, entity.VerificationRequirement) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLotteryPhaseRepository_UpdateVerificationRequirement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVerificationRequirement'
type MockLotteryPhaseRepository_UpdateVerificationRequirement_Call struct {
	*mock.Call
}

// UpdateVerificationRequirement is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.LotteryPhaseID
//   - req entity.VerificationRequirement
func (_e *MockLotteryPhaseRepository_Expecter) UpdateVerificationRequirement(ctx interface{}, id interface{}, req interface{}) *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call {
	return &MockLotteryPhaseRepository_UpdateVerificationRequirement_Call{Call: _e.mock.On("UpdateVerificationRequirement", ctx, id, req)}
}

func (_c *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call) Run(run func(ctx context.Context, id entity.LotteryPhaseID, req entity.VerificationRequirement)) *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.LotteryPhaseID), args[2].(entity.VerificationRequirement))
	})
	return _c
}

func (_c *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call) Return(_a0 *entity.LotterySalesPhase, _a1 error) *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call) RunAndReturn(run func(context.Context, entity.LotteryPhaseID, entity.VerificationRequirement) (*entity.LotterySalesPhase, error)) *MockLotteryPhaseRepository_UpdateVerificationRequirement_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLotteryPhaseRepository creates a new instance of MockLotteryPhaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLotteryPhaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLotteryPhaseRepository {
	mock := &MockLotteryPhaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
