// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAdminAreaResolver is an autogenerated mock type for the AdminAreaResolver type
type MockAdminAreaResolver struct {
	mock.Mock
}

type MockAdminAreaResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminAreaResolver) EXPECT() *MockAdminAreaResolver_Expecter {
	return &MockAdminAreaResolver_Expecter{mock: &_m.Mock}
}

// DisplayName provides a mock function with given fields: code, lang
func (_m *MockAdminAreaResolver) DisplayName(code string, lang string) string {
	ret := _m.Called(code, lang)

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(code, lang)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAdminAreaResolver_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockAdminAreaResolver_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
//   - code string
//   - lang string
func (_e *MockAdminAreaResolver_Expecter) DisplayName(code interface{}, lang interface{}) *MockAdminAreaResolver_DisplayName_Call {
	return &MockAdminAreaResolver_DisplayName_Call{Call: _e.mock.On("DisplayName", code, lang)}
}

func (_c *MockAdminAreaResolver_DisplayName_Call) Run(run func(code string, lang string)) *MockAdminAreaResolver_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAdminAreaResolver_DisplayName_Call) Return(_a0 string) *MockAdminAreaResolver_DisplayName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminAreaResolver_DisplayName_Call) RunAndReturn(run func(string, string) string) *MockAdminAreaResolver_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminAreaResolver creates a new instance of MockAdminAreaResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminAreaResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminAreaResolver {
	mock := &MockAdminAreaResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
