// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSeriesRepository is an autogenerated mock type for the SeriesRepository type
type MockSeriesRepository struct {
	mock.Mock
}

type MockSeriesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeriesRepository) EXPECT() *MockSeriesRepository_Expecter {
	return &MockSeriesRepository_Expecter{mock: &_m.Mock}
}

// ClearMerchURL provides a mock function with given fields: ctx, seriesID
func (_m *MockSeriesRepository) ClearMerchURL(ctx context.Context, seriesID string) error {
	ret := _m.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for ClearMerchURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, seriesID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeriesRepository_ClearMerchURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearMerchURL'
type MockSeriesRepository_ClearMerchURL_Call struct {
	*mock.Call
}

// ClearMerchURL is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID string
func (_e *MockSeriesRepository_Expecter) ClearMerchURL(ctx interface{}, seriesID interface{}) *MockSeriesRepository_ClearMerchURL_Call {
	return &MockSeriesRepository_ClearMerchURL_Call{Call: _e.mock.On("ClearMerchURL", ctx, seriesID)}
}

func (_c *MockSeriesRepository_ClearMerchURL_Call) Run(run func(ctx context.Context, seriesID string)) *MockSeriesRepository_ClearMerchURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSeriesRepository_ClearMerchURL_Call) Return(_a0 error) *MockSeriesRepository_ClearMerchURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeriesRepository_ClearMerchURL_Call) RunAndReturn(run func(context.Context, string) error) *MockSeriesRepository_ClearMerchURL_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, series
func (_m *MockSeriesRepository) Create(ctx context.Context, series ...*entity.Series) ([]string, error) {
	_va := make([]interface{}, len(series))
	for _i := range series {
		_va[_i] = series[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.Series) ([]string, error)); ok {
		return rf(ctx, series...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.Series) []string); ok {
		r0 = rf(ctx, series...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...*entity.Series) error); ok {
		r1 = rf(ctx, series...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeriesRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSeriesRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - series ...*entity.Series
func (_e *MockSeriesRepository_Expecter) Create(ctx interface{}, series ...interface{}) *MockSeriesRepository_Create_Call {
	return &MockSeriesRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx}, series...)...)}
}

func (_c *MockSeriesRepository_Create_Call) Run(run func(ctx context.Context, series ...*entity.Series)) *MockSeriesRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*entity.Series, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*entity.Series)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockSeriesRepository_Create_Call) Return(_a0 []string, _a1 error) *MockSeriesRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeriesRepository_Create_Call) RunAndReturn(run func(context.Context, ...*entity.Series) ([]string, error)) *MockSeriesRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockSeriesRepository) Get(ctx context.Context, id string) (*entity.Series, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Series
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Series, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Series); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Series)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeriesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSeriesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSeriesRepository_Expecter) Get(ctx interface{}, id interface{}) *MockSeriesRepository_Get_Call {
	return &MockSeriesRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSeriesRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockSeriesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSeriesRepository_Get_Call) Return(_a0 *entity.Series, _a1 error) *MockSeriesRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeriesRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*entity.Series, error)) *MockSeriesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByIDs provides a mock function with given fields: ctx, ids
func (_m *MockSeriesRepository) ListByIDs(ctx context.Context, ids []string) ([]*entity.Series, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListByIDs")
	}

	var r0 []*entity.Series
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.Series, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entity.Series); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Series)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeriesRepository_ListByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByIDs'
type MockSeriesRepository_ListByIDs_Call struct {
	*mock.Call
}

// ListByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockSeriesRepository_Expecter) ListByIDs(ctx interface{}, ids interface{}) *MockSeriesRepository_ListByIDs_Call {
	return &MockSeriesRepository_ListByIDs_Call{Call: _e.mock.On("ListByIDs", ctx, ids)}
}

func (_c *MockSeriesRepository_ListByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockSeriesRepository_ListByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockSeriesRepository_ListByIDs_Call) Return(_a0 []*entity.Series, _a1 error) *MockSeriesRepository_ListByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeriesRepository_ListByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*entity.Series, error)) *MockSeriesRepository_ListByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeriesInMerchWindow provides a mock function with given fields: ctx, window
func (_m *MockSeriesRepository) ListSeriesInMerchWindow(ctx context.Context, window time.Duration) ([]*entity.MerchCandidate, error) {
	ret := _m.Called(ctx, window)

	if len(ret) == 0 {
		panic("no return value specified for ListSeriesInMerchWindow")
	}

	var r0 []*entity.MerchCandidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) ([]*entity.MerchCandidate, error)); ok {
		return rf(ctx, window)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) []*entity.MerchCandidate); ok {
		r0 = rf(ctx, window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.MerchCandidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, window)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeriesRepository_ListSeriesInMerchWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeriesInMerchWindow'
type MockSeriesRepository_ListSeriesInMerchWindow_Call struct {
	*mock.Call
}

// ListSeriesInMerchWindow is a helper method to define mock.On call
//   - ctx context.Context
//   - window time.Duration
func (_e *MockSeriesRepository_Expecter) ListSeriesInMerchWindow(ctx interface{}, window interface{}) *MockSeriesRepository_ListSeriesInMerchWindow_Call {
	return &MockSeriesRepository_ListSeriesInMerchWindow_Call{Call: _e.mock.On("ListSeriesInMerchWindow", ctx, window)}
}

func (_c *MockSeriesRepository_ListSeriesInMerchWindow_Call) Run(run func(ctx context.Context, window time.Duration)) *MockSeriesRepository_ListSeriesInMerchWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockSeriesRepository_ListSeriesInMerchWindow_Call) Return(_a0 []*entity.MerchCandidate, _a1 error) *MockSeriesRepository_ListSeriesInMerchWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeriesRepository_ListSeriesInMerchWindow_Call) RunAndReturn(run func(context.Context, time.Duration) ([]*entity.MerchCandidate, error)) *MockSeriesRepository_ListSeriesInMerchWindow_Call {
	_c.Call.Return(run)
	return _c
}

// SetMerchURL provides a mock function with given fields: ctx, seriesID, merchURL
func (_m *MockSeriesRepository) SetMerchURL(ctx context.Context, seriesID string, merchURL string) error {
	ret := _m.Called(ctx, seriesID, merchURL)

	if len(ret) == 0 {
		panic("no return value specified for SetMerchURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, seriesID, merchURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeriesRepository_SetMerchURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMerchURL'
type MockSeriesRepository_SetMerchURL_Call struct {
	*mock.Call
}

// SetMerchURL is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID string
//   - merchURL string
func (_e *MockSeriesRepository_Expecter) SetMerchURL(ctx interface{}, seriesID interface{}, merchURL interface{}) *MockSeriesRepository_SetMerchURL_Call {
	return &MockSeriesRepository_SetMerchURL_Call{Call: _e.mock.On("SetMerchURL", ctx, seriesID, merchURL)}
}

func (_c *MockSeriesRepository_SetMerchURL_Call) Run(run func(ctx context.Context, seriesID string, merchURL string)) *MockSeriesRepository_SetMerchURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSeriesRepository_SetMerchURL_Call) Return(_a0 error) *MockSeriesRepository_SetMerchURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeriesRepository_SetMerchURL_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSeriesRepository_SetMerchURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeriesRepository creates a new instance of MockSeriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeriesRepository {
	mock := &MockSeriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
