// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVenueRepository creates a new instance of MockVenueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueRepository {
	mock := &MockVenueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVenueRepository is an autogenerated mock type for the VenueRepository type
type MockVenueRepository struct {
	mock.Mock
}

type MockVenueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueRepository) EXPECT() *MockVenueRepository_Expecter {
	return &MockVenueRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) Create(ctx context.Context, venue *entity.Venue) error {
	ret := _mock.Called(ctx, venue)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Venue) error); ok {
		r0 = returnFunc(ctx, venue)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVenueRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVenueRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - venue *entity.Venue
func (_e *MockVenueRepository_Expecter) Create(ctx interface{}, venue interface{}) *MockVenueRepository_Create_Call {
	return &MockVenueRepository_Create_Call{Call: _e.mock.On("Create", ctx, venue)}
}

func (_c *MockVenueRepository_Create_Call) Run(run func(ctx context.Context, venue *entity.Venue)) *MockVenueRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Venue
		if args[1] != nil {
			arg1 = args[1].(*entity.Venue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_Create_Call) Return(err error) *MockVenueRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVenueRepository_Create_Call) RunAndReturn(run func(ctx context.Context, venue *entity.Venue) error) *MockVenueRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) Get(ctx context.Context, id string) (*entity.Venue, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Venue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Venue, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Venue); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVenueRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockVenueRepository_Expecter) Get(ctx interface{}, id interface{}) *MockVenueRepository_Get_Call {
	return &MockVenueRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockVenueRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockVenueRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_Get_Call) Return(venue *entity.Venue, err error) *MockVenueRepository_Get_Call {
	_c.Call.Return(venue, err)
	return _c
}

func (_c *MockVenueRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Venue, error)) *MockVenueRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockVenueRepository
func (_mock *MockVenueRepository) GetByName(ctx context.Context, name string) (*entity.Venue, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Venue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Venue, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Venue); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVenueRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockVenueRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVenueRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockVenueRepository_GetByName_Call {
	return &MockVenueRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockVenueRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockVenueRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVenueRepository_GetByName_Call) Return(venue *entity.Venue, err error) *MockVenueRepository_GetByName_Call {
	_c.Call.Return(venue, err)
	return _c
}

func (_c *MockVenueRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Venue, error)) *MockVenueRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}
