// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockUserArtistSubscriptionRepository is an autogenerated mock type for the UserArtistSubscriptionRepository type
type MockUserArtistSubscriptionRepository struct {
	mock.Mock
}

type MockUserArtistSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserArtistSubscriptionRepository) EXPECT() *MockUserArtistSubscriptionRepository_Expecter {
	return &MockUserArtistSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, id
func (_m *MockUserArtistSubscriptionRepository) Activate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserArtistSubscriptionRepository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockUserArtistSubscriptionRepository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserArtistSubscriptionRepository_Expecter) Activate(ctx interface{}, id interface{}) *MockUserArtistSubscriptionRepository_Activate_Call {
	return &MockUserArtistSubscriptionRepository_Activate_Call{Call: _e.mock.On("Activate", ctx, id)}
}

func (_c *MockUserArtistSubscriptionRepository_Activate_Call) Run(run func(ctx context.Context, id string)) *MockUserArtistSubscriptionRepository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Activate_Call) Return(_a0 error) *MockUserArtistSubscriptionRepository_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Activate_Call) RunAndReturn(run func(context.Context, string) error) *MockUserArtistSubscriptionRepository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, params
func (_m *MockUserArtistSubscriptionRepository) Create(ctx context.Context, params *entity.NewUserArtistSubscription) (*entity.UserArtistSubscription, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserArtistSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.NewUserArtistSubscription) (*entity.UserArtistSubscription, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.NewUserArtistSubscription) *entity.UserArtistSubscription); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserArtistSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.NewUserArtistSubscription) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArtistSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserArtistSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params *entity.NewUserArtistSubscription
func (_e *MockUserArtistSubscriptionRepository_Expecter) Create(ctx interface{}, params interface{}) *MockUserArtistSubscriptionRepository_Create_Call {
	return &MockUserArtistSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockUserArtistSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, params *entity.NewUserArtistSubscription)) *MockUserArtistSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.NewUserArtistSubscription))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Create_Call) Return(_a0 *entity.UserArtistSubscription, _a1 error) *MockUserArtistSubscriptionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.NewUserArtistSubscription) (*entity.UserArtistSubscription, error)) *MockUserArtistSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockUserArtistSubscriptionRepository) Deactivate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserArtistSubscriptionRepository_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockUserArtistSubscriptionRepository_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserArtistSubscriptionRepository_Expecter) Deactivate(ctx interface{}, id interface{}) *MockUserArtistSubscriptionRepository_Deactivate_Call {
	return &MockUserArtistSubscriptionRepository_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockUserArtistSubscriptionRepository_Deactivate_Call) Run(run func(ctx context.Context, id string)) *MockUserArtistSubscriptionRepository_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Deactivate_Call) Return(_a0 error) *MockUserArtistSubscriptionRepository_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Deactivate_Call) RunAndReturn(run func(context.Context, string) error) *MockUserArtistSubscriptionRepository_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserArtistSubscriptionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserArtistSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserArtistSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserArtistSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserArtistSubscriptionRepository_Delete_Call {
	return &MockUserArtistSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserArtistSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserArtistSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Delete_Call) Return(_a0 error) *MockUserArtistSubscriptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUserArtistSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUserArtistSubscriptionRepository) Get(ctx context.Context, id string) (*entity.UserArtistSubscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.UserArtistSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.UserArtistSubscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.UserArtistSubscription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserArtistSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArtistSubscriptionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserArtistSubscriptionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserArtistSubscriptionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockUserArtistSubscriptionRepository_Get_Call {
	return &MockUserArtistSubscriptionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUserArtistSubscriptionRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockUserArtistSubscriptionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Get_Call) Return(_a0 *entity.UserArtistSubscription, _a1 error) *MockUserArtistSubscriptionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*entity.UserArtistSubscription, error)) *MockUserArtistSubscriptionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByArtist provides a mock function with given fields: ctx, artistID, limit, offset
func (_m *MockUserArtistSubscriptionRepository) GetByArtist(ctx context.Context, artistID string, limit int, offset int) ([]*entity.UserArtistSubscription, error) {
	ret := _m.Called(ctx, artistID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByArtist")
	}

	var r0 []*entity.UserArtistSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.UserArtistSubscription, error)); ok {
		return rf(ctx, artistID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.UserArtistSubscription); ok {
		r0 = rf(ctx, artistID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserArtistSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, artistID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArtistSubscriptionRepository_GetByArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByArtist'
type MockUserArtistSubscriptionRepository_GetByArtist_Call struct {
	*mock.Call
}

// GetByArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
//   - limit int
//   - offset int
func (_e *MockUserArtistSubscriptionRepository_Expecter) GetByArtist(ctx interface{}, artistID interface{}, limit interface{}, offset interface{}) *MockUserArtistSubscriptionRepository_GetByArtist_Call {
	return &MockUserArtistSubscriptionRepository_GetByArtist_Call{Call: _e.mock.On("GetByArtist", ctx, artistID, limit, offset)}
}

func (_c *MockUserArtistSubscriptionRepository_GetByArtist_Call) Run(run func(ctx context.Context, artistID string, limit int, offset int)) *MockUserArtistSubscriptionRepository_GetByArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByArtist_Call) Return(_a0 []*entity.UserArtistSubscription, _a1 error) *MockUserArtistSubscriptionRepository_GetByArtist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByArtist_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.UserArtistSubscription, error)) *MockUserArtistSubscriptionRepository_GetByArtist_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockUserArtistSubscriptionRepository) GetByUser(ctx context.Context, userID string, limit int, offset int) ([]*entity.UserArtistSubscription, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*entity.UserArtistSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.UserArtistSubscription, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.UserArtistSubscription); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserArtistSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArtistSubscriptionRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockUserArtistSubscriptionRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockUserArtistSubscriptionRepository_Expecter) GetByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockUserArtistSubscriptionRepository_GetByUser_Call {
	return &MockUserArtistSubscriptionRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID, limit, offset)}
}

func (_c *MockUserArtistSubscriptionRepository_GetByUser_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockUserArtistSubscriptionRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByUser_Call) Return(_a0 []*entity.UserArtistSubscription, _a1 error) *MockUserArtistSubscriptionRepository_GetByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByUser_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.UserArtistSubscription, error)) *MockUserArtistSubscriptionRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndArtist provides a mock function with given fields: ctx, userID, artistID
func (_m *MockUserArtistSubscriptionRepository) GetByUserAndArtist(ctx context.Context, userID string, artistID string) (*entity.UserArtistSubscription, error) {
	ret := _m.Called(ctx, userID, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndArtist")
	}

	var r0 *entity.UserArtistSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.UserArtistSubscription, error)); ok {
		return rf(ctx, userID, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.UserArtistSubscription); ok {
		r0 = rf(ctx, userID, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserArtistSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndArtist'
type MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call struct {
	*mock.Call
}

// GetByUserAndArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - artistID string
func (_e *MockUserArtistSubscriptionRepository_Expecter) GetByUserAndArtist(ctx interface{}, userID interface{}, artistID interface{}) *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call {
	return &MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call{Call: _e.mock.On("GetByUserAndArtist", ctx, userID, artistID)}
}

func (_c *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call) Run(run func(ctx context.Context, userID string, artistID string)) *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call) Return(_a0 *entity.UserArtistSubscription, _a1 error) *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call) RunAndReturn(run func(context.Context, string, string) (*entity.UserArtistSubscription, error)) *MockUserArtistSubscriptionRepository_GetByUserAndArtist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserArtistSubscriptionRepository creates a new instance of MockUserArtistSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserArtistSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserArtistSubscriptionRepository {
	mock := &MockUserArtistSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
