// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConcertRepository creates a new instance of MockConcertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcertRepository {
	mock := &MockConcertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConcertRepository is an autogenerated mock type for the ConcertRepository type
type MockConcertRepository struct {
	mock.Mock
}

type MockConcertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcertRepository) EXPECT() *MockConcertRepository_Expecter {
	return &MockConcertRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockConcertRepository
func (_mock *MockConcertRepository) Create(ctx context.Context, concert *entity.Concert) error {
	ret := _mock.Called(ctx, concert)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Concert) error); ok {
		r0 = returnFunc(ctx, concert)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConcertRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConcertRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - concert *entity.Concert
func (_e *MockConcertRepository_Expecter) Create(ctx interface{}, concert interface{}) *MockConcertRepository_Create_Call {
	return &MockConcertRepository_Create_Call{Call: _e.mock.On("Create", ctx, concert)}
}

func (_c *MockConcertRepository_Create_Call) Run(run func(ctx context.Context, concert *entity.Concert)) *MockConcertRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Concert
		if args[1] != nil {
			arg1 = args[1].(*entity.Concert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConcertRepository_Create_Call) Return(err error) *MockConcertRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConcertRepository_Create_Call) RunAndReturn(run func(ctx context.Context, concert *entity.Concert) error) *MockConcertRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByArtist provides a mock function for the type MockConcertRepository
func (_mock *MockConcertRepository) ListByArtist(ctx context.Context, artistID string, upcomingOnly bool) ([]*entity.Concert, error) {
	ret := _mock.Called(ctx, artistID, upcomingOnly)

	if len(ret) == 0 {
		panic("no return value specified for ListByArtist")
	}

	var r0 []*entity.Concert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) ([]*entity.Concert, error)); ok {
		return returnFunc(ctx, artistID, upcomingOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) []*entity.Concert); ok {
		r0 = returnFunc(ctx, artistID, upcomingOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, artistID, upcomingOnly)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConcertRepository_ListByArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByArtist'
type MockConcertRepository_ListByArtist_Call struct {
	*mock.Call
}

// ListByArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
//   - upcomingOnly bool
func (_e *MockConcertRepository_Expecter) ListByArtist(ctx interface{}, artistID interface{}, upcomingOnly interface{}) *MockConcertRepository_ListByArtist_Call {
	return &MockConcertRepository_ListByArtist_Call{Call: _e.mock.On("ListByArtist", ctx, artistID, upcomingOnly)}
}

func (_c *MockConcertRepository_ListByArtist_Call) Run(run func(ctx context.Context, artistID string, upcomingOnly bool)) *MockConcertRepository_ListByArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConcertRepository_ListByArtist_Call) Return(concerts []*entity.Concert, err error) *MockConcertRepository_ListByArtist_Call {
	_c.Call.Return(concerts, err)
	return _c
}

func (_c *MockConcertRepository_ListByArtist_Call) RunAndReturn(run func(ctx context.Context, artistID string, upcomingOnly bool) ([]*entity.Concert, error)) *MockConcertRepository_ListByArtist_Call {
	_c.Call.Return(run)
	return _c
}
