// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOrganizerProvisioner is an autogenerated mock type for the OrganizerProvisioner type
type MockOrganizerProvisioner struct {
	mock.Mock
}

type MockOrganizerProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizerProvisioner) EXPECT() *MockOrganizerProvisioner_Expecter {
	return &MockOrganizerProvisioner_Expecter{mock: &_m.Mock}
}

// DeactivateOperators provides a mock function with given fields: ctx, zitadelOrgID
func (_m *MockOrganizerProvisioner) DeactivateOperators(ctx context.Context, zitadelOrgID string) error {
	ret := _m.Called(ctx, zitadelOrgID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateOperators")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, zitadelOrgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizerProvisioner_DeactivateOperators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateOperators'
type MockOrganizerProvisioner_DeactivateOperators_Call struct {
	*mock.Call
}

// DeactivateOperators is a helper method to define mock.On call
//   - ctx context.Context
//   - zitadelOrgID string
func (_e *MockOrganizerProvisioner_Expecter) DeactivateOperators(ctx interface{}, zitadelOrgID interface{}) *MockOrganizerProvisioner_DeactivateOperators_Call {
	return &MockOrganizerProvisioner_DeactivateOperators_Call{Call: _e.mock.On("DeactivateOperators", ctx, zitadelOrgID)}
}

func (_c *MockOrganizerProvisioner_DeactivateOperators_Call) Run(run func(ctx context.Context, zitadelOrgID string)) *MockOrganizerProvisioner_DeactivateOperators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizerProvisioner_DeactivateOperators_Call) Return(_a0 error) *MockOrganizerProvisioner_DeactivateOperators_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizerProvisioner_DeactivateOperators_Call) RunAndReturn(run func(context.Context, string) error) *MockOrganizerProvisioner_DeactivateOperators_Call {
	_c.Call.Return(run)
	return _c
}

// ProvisionTenant provides a mock function with given fields: ctx, organizerID, name, operatorEmail
func (_m *MockOrganizerProvisioner) ProvisionTenant(ctx context.Context, organizerID string, name string, operatorEmail string) (string, error) {
	ret := _m.Called(ctx, organizerID, name, operatorEmail)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionTenant")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, organizerID, name, operatorEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, organizerID, name, operatorEmail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, organizerID, name, operatorEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizerProvisioner_ProvisionTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionTenant'
type MockOrganizerProvisioner_ProvisionTenant_Call struct {
	*mock.Call
}

// ProvisionTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - organizerID string
//   - name string
//   - operatorEmail string
func (_e *MockOrganizerProvisioner_Expecter) ProvisionTenant(ctx interface{}, organizerID interface{}, name interface{}, operatorEmail interface{}) *MockOrganizerProvisioner_ProvisionTenant_Call {
	return &MockOrganizerProvisioner_ProvisionTenant_Call{Call: _e.mock.On("ProvisionTenant", ctx, organizerID, name, operatorEmail)}
}

func (_c *MockOrganizerProvisioner_ProvisionTenant_Call) Run(run func(ctx context.Context, organizerID string, name string, operatorEmail string)) *MockOrganizerProvisioner_ProvisionTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockOrganizerProvisioner_ProvisionTenant_Call) Return(zitadelOrgID string, err error) *MockOrganizerProvisioner_ProvisionTenant_Call {
	_c.Call.Return(zitadelOrgID, err)
	return _c
}

func (_c *MockOrganizerProvisioner_ProvisionTenant_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockOrganizerProvisioner_ProvisionTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizerProvisioner creates a new instance of MockOrganizerProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizerProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizerProvisioner {
	mock := &MockOrganizerProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
