// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockConcertSearcher is an autogenerated mock type for the ConcertSearcher type
type MockConcertSearcher struct {
	mock.Mock
}

type MockConcertSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcertSearcher) EXPECT() *MockConcertSearcher_Expecter {
	return &MockConcertSearcher_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, artist, officialSite, from
func (_m *MockConcertSearcher) Search(ctx context.Context, artist *entity.Artist, officialSite *entity.OfficialSite, from time.Time) ([]*entity.ScrapedConcert, error) {
	ret := _m.Called(ctx, artist, officialSite, from)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.ScrapedConcert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist, *entity.OfficialSite, time.Time) ([]*entity.ScrapedConcert, error)); ok {
		return rf(ctx, artist, officialSite, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist, *entity.OfficialSite, time.Time) []*entity.ScrapedConcert); ok {
		r0 = rf(ctx, artist, officialSite, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ScrapedConcert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Artist, *entity.OfficialSite, time.Time) error); ok {
		r1 = rf(ctx, artist, officialSite, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertSearcher_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockConcertSearcher_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
//   - officialSite *entity.OfficialSite
//   - from time.Time
func (_e *MockConcertSearcher_Expecter) Search(ctx interface{}, artist interface{}, officialSite interface{}, from interface{}) *MockConcertSearcher_Search_Call {
	return &MockConcertSearcher_Search_Call{Call: _e.mock.On("Search", ctx, artist, officialSite, from)}
}

func (_c *MockConcertSearcher_Search_Call) Run(run func(ctx context.Context, artist *entity.Artist, officialSite *entity.OfficialSite, from time.Time)) *MockConcertSearcher_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Artist), args[2].(*entity.OfficialSite), args[3].(time.Time))
	})
	return _c
}

func (_c *MockConcertSearcher_Search_Call) Return(_a0 []*entity.ScrapedConcert, _a1 error) *MockConcertSearcher_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertSearcher_Search_Call) RunAndReturn(run func(context.Context, *entity.Artist, *entity.OfficialSite, time.Time) ([]*entity.ScrapedConcert, error)) *MockConcertSearcher_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConcertSearcher creates a new instance of MockConcertSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcertSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcertSearcher {
	mock := &MockConcertSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
