// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMerchLivenessChecker is an autogenerated mock type for the MerchLivenessChecker type
type MockMerchLivenessChecker struct {
	mock.Mock
}

type MockMerchLivenessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchLivenessChecker) EXPECT() *MockMerchLivenessChecker_Expecter {
	return &MockMerchLivenessChecker_Expecter{mock: &_m.Mock}
}

// IsDeadLink provides a mock function with given fields: ctx, url
func (_m *MockMerchLivenessChecker) IsDeadLink(ctx context.Context, url string) bool {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for IsDeadLink")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMerchLivenessChecker_IsDeadLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDeadLink'
type MockMerchLivenessChecker_IsDeadLink_Call struct {
	*mock.Call
}

// IsDeadLink is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockMerchLivenessChecker_Expecter) IsDeadLink(ctx interface{}, url interface{}) *MockMerchLivenessChecker_IsDeadLink_Call {
	return &MockMerchLivenessChecker_IsDeadLink_Call{Call: _e.mock.On("IsDeadLink", ctx, url)}
}

func (_c *MockMerchLivenessChecker_IsDeadLink_Call) Run(run func(ctx context.Context, url string)) *MockMerchLivenessChecker_IsDeadLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMerchLivenessChecker_IsDeadLink_Call) Return(_a0 bool) *MockMerchLivenessChecker_IsDeadLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchLivenessChecker_IsDeadLink_Call) RunAndReturn(run func(context.Context, string) bool) *MockMerchLivenessChecker_IsDeadLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchLivenessChecker creates a new instance of MockMerchLivenessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchLivenessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchLivenessChecker {
	mock := &MockMerchLivenessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
