// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockArtistSearcher creates a new instance of MockArtistSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistSearcher {
	mock := &MockArtistSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtistSearcher is an autogenerated mock type for the ArtistSearcher type
type MockArtistSearcher struct {
	mock.Mock
}

type MockArtistSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistSearcher) EXPECT() *MockArtistSearcher_Expecter {
	return &MockArtistSearcher_Expecter{mock: &_m.Mock}
}

// ListSimilar provides a mock function for the type MockArtistSearcher
func (_mock *MockArtistSearcher) ListSimilar(ctx context.Context, artist *entity.Artist, limit int32) ([]*entity.Artist, error) {
	ret := _mock.Called(ctx, artist, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSimilar")
	}

	var r0 []*entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Artist, int32) ([]*entity.Artist, error)); ok {
		return returnFunc(ctx, artist, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Artist, int32) []*entity.Artist); ok {
		r0 = returnFunc(ctx, artist, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Artist, int32) error); ok {
		r1 = returnFunc(ctx, artist, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistSearcher_ListSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSimilar'
type MockArtistSearcher_ListSimilar_Call struct {
	*mock.Call
}

// ListSimilar is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
//   - limit int32
func (_e *MockArtistSearcher_Expecter) ListSimilar(ctx interface{}, artist interface{}, limit interface{}) *MockArtistSearcher_ListSimilar_Call {
	return &MockArtistSearcher_ListSimilar_Call{Call: _e.mock.On("ListSimilar", ctx, artist, limit)}
}

func (_c *MockArtistSearcher_ListSimilar_Call) Run(run func(ctx context.Context, artist *entity.Artist, limit int32)) *MockArtistSearcher_ListSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Artist
		if args[1] != nil {
			arg1 = args[1].(*entity.Artist)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtistSearcher_ListSimilar_Call) Return(artists []*entity.Artist, err error) *MockArtistSearcher_ListSimilar_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistSearcher_ListSimilar_Call) RunAndReturn(run func(ctx context.Context, artist *entity.Artist, limit int32) ([]*entity.Artist, error)) *MockArtistSearcher_ListSimilar_Call {
	_c.Call.Return(run)
	return _c
}

// ListTop provides a mock function for the type MockArtistSearcher
func (_mock *MockArtistSearcher) ListTop(ctx context.Context, country string, tag string, limit int32) ([]*entity.Artist, error) {
	ret := _mock.Called(ctx, country, tag, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTop")
	}

	var r0 []*entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int32) ([]*entity.Artist, error)); ok {
		return returnFunc(ctx, country, tag, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int32) []*entity.Artist); ok {
		r0 = returnFunc(ctx, country, tag, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int32) error); ok {
		r1 = returnFunc(ctx, country, tag, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistSearcher_ListTop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTop'
type MockArtistSearcher_ListTop_Call struct {
	*mock.Call
}

// ListTop is a helper method to define mock.On call
//   - ctx context.Context
//   - country string
//   - tag string
//   - limit int32
func (_e *MockArtistSearcher_Expecter) ListTop(ctx interface{}, country interface{}, tag interface{}, limit interface{}) *MockArtistSearcher_ListTop_Call {
	return &MockArtistSearcher_ListTop_Call{Call: _e.mock.On("ListTop", ctx, country, tag, limit)}
}

func (_c *MockArtistSearcher_ListTop_Call) Run(run func(ctx context.Context, country string, tag string, limit int32)) *MockArtistSearcher_ListTop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockArtistSearcher_ListTop_Call) Return(artists []*entity.Artist, err error) *MockArtistSearcher_ListTop_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistSearcher_ListTop_Call) RunAndReturn(run func(ctx context.Context, country string, tag string, limit int32) ([]*entity.Artist, error)) *MockArtistSearcher_ListTop_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockArtistSearcher
func (_mock *MockArtistSearcher) Search(ctx context.Context, query string) ([]*entity.Artist, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Artist, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Artist); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistSearcher_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockArtistSearcher_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockArtistSearcher_Expecter) Search(ctx interface{}, query interface{}) *MockArtistSearcher_Search_Call {
	return &MockArtistSearcher_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockArtistSearcher_Search_Call) Run(run func(ctx context.Context, query string)) *MockArtistSearcher_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistSearcher_Search_Call) Return(artists []*entity.Artist, err error) *MockArtistSearcher_Search_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistSearcher_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]*entity.Artist, error)) *MockArtistSearcher_Search_Call {
	_c.Call.Return(run)
	return _c
}
