// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReservationRepository is an autogenerated mock type for the ReservationRepository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx, id, now
func (_m *MockReservationRepository) Commit(ctx context.Context, id entity.ReservationID, now time.Time) (entity.CommitOutcome, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 entity.CommitOutcome
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) (entity.CommitOutcome, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) entity.CommitOutcome); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(entity.CommitOutcome)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ReservationID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockReservationRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - now time.Time
func (_e *MockReservationRepository_Expecter) Commit(ctx interface{}, id interface{}, now interface{}) *MockReservationRepository_Commit_Call {
	return &MockReservationRepository_Commit_Call{Call: _e.mock.On("Commit", ctx, id, now)}
}

func (_c *MockReservationRepository_Commit_Call) Run(run func(ctx context.Context, id entity.ReservationID, now time.Time)) *MockReservationRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_Commit_Call) Return(_a0 entity.CommitOutcome, _a1 error) *MockReservationRepository_Commit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_Commit_Call) RunAndReturn(run func(context.Context, entity.ReservationID, time.Time) (entity.CommitOutcome, error)) *MockReservationRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) Get(ctx context.Context, id entity.ReservationID) (*entity.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID) (*entity.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID) *entity.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ReservationID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReservationRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
func (_e *MockReservationRepository_Expecter) Get(ctx interface{}, id interface{}) *MockReservationRepository_Get_Call {
	return &MockReservationRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockReservationRepository_Get_Call) Run(run func(ctx context.Context, id entity.ReservationID)) *MockReservationRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID))
	})
	return _c
}

func (_c *MockReservationRepository_Get_Call) Return(_a0 *entity.Reservation, _a1 error) *MockReservationRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_Get_Call) RunAndReturn(run func(context.Context, entity.ReservationID) (*entity.Reservation, error)) *MockReservationRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAuthorizationRef provides a mock function with given fields: ctx, authorizationRef
func (_m *MockReservationRepository) GetByAuthorizationRef(ctx context.Context, authorizationRef string) (*entity.Reservation, error) {
	ret := _m.Called(ctx, authorizationRef)

	if len(ret) == 0 {
		panic("no return value specified for GetByAuthorizationRef")
	}

	var r0 *entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Reservation, error)); ok {
		return rf(ctx, authorizationRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Reservation); ok {
		r0 = rf(ctx, authorizationRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authorizationRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetByAuthorizationRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAuthorizationRef'
type MockReservationRepository_GetByAuthorizationRef_Call struct {
	*mock.Call
}

// GetByAuthorizationRef is a helper method to define mock.On call
//   - ctx context.Context
//   - authorizationRef string
func (_e *MockReservationRepository_Expecter) GetByAuthorizationRef(ctx interface{}, authorizationRef interface{}) *MockReservationRepository_GetByAuthorizationRef_Call {
	return &MockReservationRepository_GetByAuthorizationRef_Call{Call: _e.mock.On("GetByAuthorizationRef", ctx, authorizationRef)}
}

func (_c *MockReservationRepository_GetByAuthorizationRef_Call) Run(run func(ctx context.Context, authorizationRef string)) *MockReservationRepository_GetByAuthorizationRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetByAuthorizationRef_Call) Return(_a0 *entity.Reservation, _a1 error) *MockReservationRepository_GetByAuthorizationRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetByAuthorizationRef_Call) RunAndReturn(run func(context.Context, string) (*entity.Reservation, error)) *MockReservationRepository_GetByAuthorizationRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateHeld provides a mock function with given fields: ctx, saleID, userID, count, now
func (_m *MockReservationRepository) GetOrCreateHeld(ctx context.Context, saleID entity.TicketSaleID, userID entity.UserID, count int, now time.Time) (*entity.Reservation, error) {
	ret := _m.Called(ctx, saleID, userID, count, now)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateHeld")
	}

	var r0 *entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketSaleID, entity.UserID, int, time.Time) (*entity.Reservation, error)); ok {
		return rf(ctx, saleID, userID, count, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketSaleID, entity.UserID, int, time.Time) *entity.Reservation); ok {
		r0 = rf(ctx, saleID, userID, count, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TicketSaleID, entity.UserID, int, time.Time) error); ok {
		r1 = rf(ctx, saleID, userID, count, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetOrCreateHeld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateHeld'
type MockReservationRepository_GetOrCreateHeld_Call struct {
	*mock.Call
}

// GetOrCreateHeld is a helper method to define mock.On call
//   - ctx context.Context
//   - saleID entity.TicketSaleID
//   - userID entity.UserID
//   - count int
//   - now time.Time
func (_e *MockReservationRepository_Expecter) GetOrCreateHeld(ctx interface{}, saleID interface{}, userID interface{}, count interface{}, now interface{}) *MockReservationRepository_GetOrCreateHeld_Call {
	return &MockReservationRepository_GetOrCreateHeld_Call{Call: _e.mock.On("GetOrCreateHeld", ctx, saleID, userID, count, now)}
}

func (_c *MockReservationRepository_GetOrCreateHeld_Call) Run(run func(ctx context.Context, saleID entity.TicketSaleID, userID entity.UserID, count int, now time.Time)) *MockReservationRepository_GetOrCreateHeld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TicketSaleID), args[2].(entity.UserID), args[3].(int), args[4].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_GetOrCreateHeld_Call) Return(_a0 *entity.Reservation, _a1 error) *MockReservationRepository_GetOrCreateHeld_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetOrCreateHeld_Call) RunAndReturn(run func(context.Context, entity.TicketSaleID, entity.UserID, int, time.Time) (*entity.Reservation, error)) *MockReservationRepository_GetOrCreateHeld_Call {
	_c.Call.Return(run)
	return _c
}

// ListDue provides a mock function with given fields: ctx, now
func (_m *MockReservationRepository) ListDue(ctx context.Context, now time.Time) ([]*entity.Reservation, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ListDue")
	}

	var r0 []*entity.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*entity.Reservation, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*entity.Reservation); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_ListDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDue'
type MockReservationRepository_ListDue_Call struct {
	*mock.Call
}

// ListDue is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockReservationRepository_Expecter) ListDue(ctx interface{}, now interface{}) *MockReservationRepository_ListDue_Call {
	return &MockReservationRepository_ListDue_Call{Call: _e.mock.On("ListDue", ctx, now)}
}

func (_c *MockReservationRepository_ListDue_Call) Run(run func(ctx context.Context, now time.Time)) *MockReservationRepository_ListDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_ListDue_Call) Return(_a0 []*entity.Reservation, _a1 error) *MockReservationRepository_ListDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_ListDue_Call) RunAndReturn(run func(context.Context, time.Time) ([]*entity.Reservation, error)) *MockReservationRepository_ListDue_Call {
	_c.Call.Return(run)
	return _c
}

// RecordAuthorizationRelease provides a mock function with given fields: ctx, id, at
func (_m *MockReservationRepository) RecordAuthorizationRelease(ctx context.Context, id entity.ReservationID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for RecordAuthorizationRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_RecordAuthorizationRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAuthorizationRelease'
type MockReservationRepository_RecordAuthorizationRelease_Call struct {
	*mock.Call
}

// RecordAuthorizationRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - at time.Time
func (_e *MockReservationRepository_Expecter) RecordAuthorizationRelease(ctx interface{}, id interface{}, at interface{}) *MockReservationRepository_RecordAuthorizationRelease_Call {
	return &MockReservationRepository_RecordAuthorizationRelease_Call{Call: _e.mock.On("RecordAuthorizationRelease", ctx, id, at)}
}

func (_c *MockReservationRepository_RecordAuthorizationRelease_Call) Run(run func(ctx context.Context, id entity.ReservationID, at time.Time)) *MockReservationRepository_RecordAuthorizationRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_RecordAuthorizationRelease_Call) Return(_a0 error) *MockReservationRepository_RecordAuthorizationRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_RecordAuthorizationRelease_Call) RunAndReturn(run func(context.Context, entity.ReservationID, time.Time) error) *MockReservationRepository_RecordAuthorizationRelease_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCapture provides a mock function with given fields: ctx, id, at
func (_m *MockReservationRepository) RecordCapture(ctx context.Context, id entity.ReservationID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for RecordCapture")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_RecordCapture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCapture'
type MockReservationRepository_RecordCapture_Call struct {
	*mock.Call
}

// RecordCapture is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - at time.Time
func (_e *MockReservationRepository_Expecter) RecordCapture(ctx interface{}, id interface{}, at interface{}) *MockReservationRepository_RecordCapture_Call {
	return &MockReservationRepository_RecordCapture_Call{Call: _e.mock.On("RecordCapture", ctx, id, at)}
}

func (_c *MockReservationRepository_RecordCapture_Call) Run(run func(ctx context.Context, id entity.ReservationID, at time.Time)) *MockReservationRepository_RecordCapture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_RecordCapture_Call) Return(_a0 error) *MockReservationRepository_RecordCapture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_RecordCapture_Call) RunAndReturn(run func(context.Context, entity.ReservationID, time.Time) error) *MockReservationRepository_RecordCapture_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, id, now
func (_m *MockReservationRepository) Release(ctx context.Context, id entity.ReservationID, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ReservationID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockReservationRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - now time.Time
func (_e *MockReservationRepository_Expecter) Release(ctx interface{}, id interface{}, now interface{}) *MockReservationRepository_Release_Call {
	return &MockReservationRepository_Release_Call{Call: _e.mock.On("Release", ctx, id, now)}
}

func (_c *MockReservationRepository_Release_Call) Run(run func(ctx context.Context, id entity.ReservationID, now time.Time)) *MockReservationRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReservationRepository_Release_Call) Return(_a0 bool, _a1 error) *MockReservationRepository_Release_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_Release_Call) RunAndReturn(run func(context.Context, entity.ReservationID, time.Time) (bool, error)) *MockReservationRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// RevertCommit provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) RevertCommit(ctx context.Context, id entity.ReservationID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevertCommit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_RevertCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertCommit'
type MockReservationRepository_RevertCommit_Call struct {
	*mock.Call
}

// RevertCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
func (_e *MockReservationRepository_Expecter) RevertCommit(ctx interface{}, id interface{}) *MockReservationRepository_RevertCommit_Call {
	return &MockReservationRepository_RevertCommit_Call{Call: _e.mock.On("RevertCommit", ctx, id)}
}

func (_c *MockReservationRepository_RevertCommit_Call) Run(run func(ctx context.Context, id entity.ReservationID)) *MockReservationRepository_RevertCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID))
	})
	return _c
}

func (_c *MockReservationRepository_RevertCommit_Call) Return(_a0 error) *MockReservationRepository_RevertCommit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_RevertCommit_Call) RunAndReturn(run func(context.Context, entity.ReservationID) error) *MockReservationRepository_RevertCommit_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function with given fields: ctx, id, fn
func (_m *MockReservationRepository) Serialize(ctx context.Context, id entity.ReservationID, fn func(context.Context) error) error {
	ret := _m.Called(ctx, id, fn)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, func(context.Context) error) error); ok {
		r0 = rf(ctx, id, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockReservationRepository_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - fn func(context.Context) error
func (_e *MockReservationRepository_Expecter) Serialize(ctx interface{}, id interface{}, fn interface{}) *MockReservationRepository_Serialize_Call {
	return &MockReservationRepository_Serialize_Call{Call: _e.mock.On("Serialize", ctx, id, fn)}
}

func (_c *MockReservationRepository_Serialize_Call) Run(run func(ctx context.Context, id entity.ReservationID, fn func(context.Context) error)) *MockReservationRepository_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockReservationRepository_Serialize_Call) Return(_a0 error) *MockReservationRepository_Serialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_Serialize_Call) RunAndReturn(run func(context.Context, entity.ReservationID, func(context.Context) error) error) *MockReservationRepository_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuthorization provides a mock function with given fields: ctx, id, identity, authorizationRef
func (_m *MockReservationRepository) SetAuthorization(ctx context.Context, id entity.ReservationID, identity entity.HolderIdentity, authorizationRef string) error {
	ret := _m.Called(ctx, id, identity, authorizationRef)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthorization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ReservationID, entity.HolderIdentity, string) error); ok {
		r0 = rf(ctx, id, identity, authorizationRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_SetAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthorization'
type MockReservationRepository_SetAuthorization_Call struct {
	*mock.Call
}

// SetAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.ReservationID
//   - identity entity.HolderIdentity
//   - authorizationRef string
func (_e *MockReservationRepository_Expecter) SetAuthorization(ctx interface{}, id interface{}, identity interface{}, authorizationRef interface{}) *MockReservationRepository_SetAuthorization_Call {
	return &MockReservationRepository_SetAuthorization_Call{Call: _e.mock.On("SetAuthorization", ctx, id, identity, authorizationRef)}
}

func (_c *MockReservationRepository_SetAuthorization_Call) Run(run func(ctx context.Context, id entity.ReservationID, identity entity.HolderIdentity, authorizationRef string)) *MockReservationRepository_SetAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ReservationID), args[2].(entity.HolderIdentity), args[3].(string))
	})
	return _c
}

func (_c *MockReservationRepository_SetAuthorization_Call) Return(_a0 error) *MockReservationRepository_SetAuthorization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_SetAuthorization_Call) RunAndReturn(run func(context.Context, entity.ReservationID, entity.HolderIdentity, string) error) *MockReservationRepository_SetAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
