// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTicketEmailParser is an autogenerated mock type for the TicketEmailParser type
type MockTicketEmailParser struct {
	mock.Mock
}

type MockTicketEmailParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketEmailParser) EXPECT() *MockTicketEmailParser_Expecter {
	return &MockTicketEmailParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: ctx, emailBody, emailType
func (_m *MockTicketEmailParser) Parse(ctx context.Context, emailBody string, emailType entity.TicketEmailType) (*entity.ParsedEmailData, error) {
	ret := _m.Called(ctx, emailBody, emailType)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *entity.ParsedEmailData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.TicketEmailType) (*entity.ParsedEmailData, error)); ok {
		return rf(ctx, emailBody, emailType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.TicketEmailType) *entity.ParsedEmailData); ok {
		r0 = rf(ctx, emailBody, emailType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParsedEmailData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.TicketEmailType) error); ok {
		r1 = rf(ctx, emailBody, emailType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketEmailParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTicketEmailParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - emailBody string
//   - emailType entity.TicketEmailType
func (_e *MockTicketEmailParser_Expecter) Parse(ctx interface{}, emailBody interface{}, emailType interface{}) *MockTicketEmailParser_Parse_Call {
	return &MockTicketEmailParser_Parse_Call{Call: _e.mock.On("Parse", ctx, emailBody, emailType)}
}

func (_c *MockTicketEmailParser_Parse_Call) Run(run func(ctx context.Context, emailBody string, emailType entity.TicketEmailType)) *MockTicketEmailParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.TicketEmailType))
	})
	return _c
}

func (_c *MockTicketEmailParser_Parse_Call) Return(_a0 *entity.ParsedEmailData, _a1 error) *MockTicketEmailParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketEmailParser_Parse_Call) RunAndReturn(run func(context.Context, string, entity.TicketEmailType) (*entity.ParsedEmailData, error)) *MockTicketEmailParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketEmailParser creates a new instance of MockTicketEmailParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketEmailParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketEmailParser {
	mock := &MockTicketEmailParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
