// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMerchSearcher is an autogenerated mock type for the MerchSearcher type
type MockMerchSearcher struct {
	mock.Mock
}

type MockMerchSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchSearcher) EXPECT() *MockMerchSearcher_Expecter {
	return &MockMerchSearcher_Expecter{mock: &_m.Mock}
}

// SearchMerchURL provides a mock function with given fields: ctx, artistName, seriesTitle
func (_m *MockMerchSearcher) SearchMerchURL(ctx context.Context, artistName string, seriesTitle string) (string, error) {
	ret := _m.Called(ctx, artistName, seriesTitle)

	if len(ret) == 0 {
		panic("no return value specified for SearchMerchURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, artistName, seriesTitle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, artistName, seriesTitle)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, artistName, seriesTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchSearcher_SearchMerchURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMerchURL'
type MockMerchSearcher_SearchMerchURL_Call struct {
	*mock.Call
}

// SearchMerchURL is a helper method to define mock.On call
//   - ctx context.Context
//   - artistName string
//   - seriesTitle string
func (_e *MockMerchSearcher_Expecter) SearchMerchURL(ctx interface{}, artistName interface{}, seriesTitle interface{}) *MockMerchSearcher_SearchMerchURL_Call {
	return &MockMerchSearcher_SearchMerchURL_Call{Call: _e.mock.On("SearchMerchURL", ctx, artistName, seriesTitle)}
}

func (_c *MockMerchSearcher_SearchMerchURL_Call) Run(run func(ctx context.Context, artistName string, seriesTitle string)) *MockMerchSearcher_SearchMerchURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMerchSearcher_SearchMerchURL_Call) Return(_a0 string, _a1 error) *MockMerchSearcher_SearchMerchURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchSearcher_SearchMerchURL_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockMerchSearcher_SearchMerchURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchSearcher creates a new instance of MockMerchSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchSearcher {
	mock := &MockMerchSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
