// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockStagedConcertRepository is an autogenerated mock type for the StagedConcertRepository type
type MockStagedConcertRepository struct {
	mock.Mock
}

type MockStagedConcertRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStagedConcertRepository) EXPECT() *MockStagedConcertRepository_Expecter {
	return &MockStagedConcertRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockStagedConcertRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStagedConcertRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStagedConcertRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStagedConcertRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockStagedConcertRepository_Delete_Call {
	return &MockStagedConcertRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockStagedConcertRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockStagedConcertRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStagedConcertRepository_Delete_Call) Return(_a0 error) *MockStagedConcertRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStagedConcertRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStagedConcertRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockStagedConcertRepository) GetByID(ctx context.Context, id string) (*entity.StagedConcert, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.StagedConcert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.StagedConcert, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.StagedConcert); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.StagedConcert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStagedConcertRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockStagedConcertRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStagedConcertRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockStagedConcertRepository_GetByID_Call {
	return &MockStagedConcertRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockStagedConcertRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockStagedConcertRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStagedConcertRepository_GetByID_Call) Return(_a0 *entity.StagedConcert, _a1 error) *MockStagedConcertRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStagedConcertRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entity.StagedConcert, error)) *MockStagedConcertRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function with given fields: ctx
func (_m *MockStagedConcertRepository) ListPending(ctx context.Context) ([]*entity.StagedConcert, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []*entity.StagedConcert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.StagedConcert, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.StagedConcert); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.StagedConcert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStagedConcertRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockStagedConcertRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStagedConcertRepository_Expecter) ListPending(ctx interface{}) *MockStagedConcertRepository_ListPending_Call {
	return &MockStagedConcertRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx)}
}

func (_c *MockStagedConcertRepository_ListPending_Call) Run(run func(ctx context.Context)) *MockStagedConcertRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStagedConcertRepository_ListPending_Call) Return(_a0 []*entity.StagedConcert, _a1 error) *MockStagedConcertRepository_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStagedConcertRepository_ListPending_Call) RunAndReturn(run func(context.Context) ([]*entity.StagedConcert, error)) *MockStagedConcertRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingDedupKeysByArtist provides a mock function with given fields: ctx, artistID
func (_m *MockStagedConcertRepository) ListPendingDedupKeysByArtist(ctx context.Context, artistID string) ([]entity.StagedConcertDedupKey, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingDedupKeysByArtist")
	}

	var r0 []entity.StagedConcertDedupKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.StagedConcertDedupKey, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.StagedConcertDedupKey); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.StagedConcertDedupKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingDedupKeysByArtist'
type MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call struct {
	*mock.Call
}

// ListPendingDedupKeysByArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockStagedConcertRepository_Expecter) ListPendingDedupKeysByArtist(ctx interface{}, artistID interface{}) *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call {
	return &MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call{Call: _e.mock.On("ListPendingDedupKeysByArtist", ctx, artistID)}
}

func (_c *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call) Run(run func(ctx context.Context, artistID string)) *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call) Return(_a0 []entity.StagedConcertDedupKey, _a1 error) *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call) RunAndReturn(run func(context.Context, string) ([]entity.StagedConcertDedupKey, error)) *MockStagedConcertRepository_ListPendingDedupKeysByArtist_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, sc
func (_m *MockStagedConcertRepository) Upsert(ctx context.Context, sc *entity.StagedConcert) error {
	ret := _m.Called(ctx, sc)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.StagedConcert) error); ok {
		r0 = rf(ctx, sc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStagedConcertRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockStagedConcertRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - sc *entity.StagedConcert
func (_e *MockStagedConcertRepository_Expecter) Upsert(ctx interface{}, sc interface{}) *MockStagedConcertRepository_Upsert_Call {
	return &MockStagedConcertRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, sc)}
}

func (_c *MockStagedConcertRepository_Upsert_Call) Run(run func(ctx context.Context, sc *entity.StagedConcert)) *MockStagedConcertRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.StagedConcert))
	})
	return _c
}

func (_c *MockStagedConcertRepository_Upsert_Call) Return(_a0 error) *MockStagedConcertRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStagedConcertRepository_Upsert_Call) RunAndReturn(run func(context.Context, *entity.StagedConcert) error) *MockStagedConcertRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStagedConcertRepository creates a new instance of MockStagedConcertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStagedConcertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStagedConcertRepository {
	mock := &MockStagedConcertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
