// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockPushSubscriptionRepository is an autogenerated mock type for the PushSubscriptionRepository type
type MockPushSubscriptionRepository struct {
	mock.Mock
}

type MockPushSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushSubscriptionRepository) EXPECT() *MockPushSubscriptionRepository_Expecter {
	return &MockPushSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sub
func (_m *MockPushSubscriptionRepository) Create(ctx context.Context, sub *entity.PushSubscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PushSubscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPushSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *entity.PushSubscription
func (_e *MockPushSubscriptionRepository_Expecter) Create(ctx interface{}, sub interface{}) *MockPushSubscriptionRepository_Create_Call {
	return &MockPushSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockPushSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, sub *entity.PushSubscription)) *MockPushSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PushSubscription))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_Create_Call) Return(_a0 error) *MockPushSubscriptionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.PushSubscription) error) *MockPushSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionRepository) Delete(ctx context.Context, userID string, endpoint string) error {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPushSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - endpoint string
func (_e *MockPushSubscriptionRepository_Expecter) Delete(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionRepository_Delete_Call {
	return &MockPushSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, userID string, endpoint string)) *MockPushSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_Delete_Call) Return(_a0 error) *MockPushSubscriptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPushSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionRepository) Get(ctx context.Context, userID string, endpoint string) (*entity.PushSubscription, error) {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.PushSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.PushSubscription, error)); ok {
		return rf(ctx, userID, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.PushSubscription); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PushSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushSubscriptionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPushSubscriptionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - endpoint string
func (_e *MockPushSubscriptionRepository_Expecter) Get(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionRepository_Get_Call {
	return &MockPushSubscriptionRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionRepository_Get_Call) Run(run func(ctx context.Context, userID string, endpoint string)) *MockPushSubscriptionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_Get_Call) Return(_a0 *entity.PushSubscription, _a1 error) *MockPushSubscriptionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushSubscriptionRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*entity.PushSubscription, error)) *MockPushSubscriptionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserIDs provides a mock function with given fields: ctx, userIDs
func (_m *MockPushSubscriptionRepository) ListByUserIDs(ctx context.Context, userIDs []string) ([]*entity.PushSubscription, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserIDs")
	}

	var r0 []*entity.PushSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.PushSubscription, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entity.PushSubscription); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PushSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushSubscriptionRepository_ListByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserIDs'
type MockPushSubscriptionRepository_ListByUserIDs_Call struct {
	*mock.Call
}

// ListByUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []string
func (_e *MockPushSubscriptionRepository_Expecter) ListByUserIDs(ctx interface{}, userIDs interface{}) *MockPushSubscriptionRepository_ListByUserIDs_Call {
	return &MockPushSubscriptionRepository_ListByUserIDs_Call{Call: _e.mock.On("ListByUserIDs", ctx, userIDs)}
}

func (_c *MockPushSubscriptionRepository_ListByUserIDs_Call) Run(run func(ctx context.Context, userIDs []string)) *MockPushSubscriptionRepository_ListByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_ListByUserIDs_Call) Return(_a0 []*entity.PushSubscription, _a1 error) *MockPushSubscriptionRepository_ListByUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushSubscriptionRepository_ListByUserIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*entity.PushSubscription, error)) *MockPushSubscriptionRepository_ListByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushSubscriptionRepository creates a new instance of MockPushSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushSubscriptionRepository {
	mock := &MockPushSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
