// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIdentityRemover is an autogenerated mock type for the IdentityRemover type
type MockIdentityRemover struct {
	mock.Mock
}

type MockIdentityRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityRemover) EXPECT() *MockIdentityRemover_Expecter {
	return &MockIdentityRemover_Expecter{mock: &_m.Mock}
}

// DeleteIdentity provides a mock function with given fields: ctx, externalID
func (_m *MockIdentityRemover) DeleteIdentity(ctx context.Context, externalID string) error {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIdentity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdentityRemover_DeleteIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIdentity'
type MockIdentityRemover_DeleteIdentity_Call struct {
	*mock.Call
}

// DeleteIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockIdentityRemover_Expecter) DeleteIdentity(ctx interface{}, externalID interface{}) *MockIdentityRemover_DeleteIdentity_Call {
	return &MockIdentityRemover_DeleteIdentity_Call{Call: _e.mock.On("DeleteIdentity", ctx, externalID)}
}

func (_c *MockIdentityRemover_DeleteIdentity_Call) Run(run func(ctx context.Context, externalID string)) *MockIdentityRemover_DeleteIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityRemover_DeleteIdentity_Call) Return(_a0 error) *MockIdentityRemover_DeleteIdentity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentityRemover_DeleteIdentity_Call) RunAndReturn(run func(context.Context, string) error) *MockIdentityRemover_DeleteIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityRemover creates a new instance of MockIdentityRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityRemover {
	mock := &MockIdentityRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
