// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) Create(ctx context.Context, params *entity.NewNotification) (*entity.Notification, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.NewNotification) (*entity.Notification, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.NewNotification) *entity.Notification); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.NewNotification) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params *entity.NewNotification
func (_e *MockNotificationRepository_Expecter) Create(ctx interface{}, params interface{}) *MockNotificationRepository_Create_Call {
	return &MockNotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockNotificationRepository_Create_Call) Run(run func(ctx context.Context, params *entity.NewNotification)) *MockNotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.NewNotification
		if args[1] != nil {
			arg1 = args[1].(*entity.NewNotification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_Create_Call) Return(notification *entity.Notification, err error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockNotificationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, params *entity.NewNotification) (*entity.Notification, error)) *MockNotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockNotificationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockNotificationRepository_Delete_Call {
	return &MockNotificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockNotificationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockNotificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) Return(err error) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) Get(ctx context.Context, id string) (*entity.Notification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Notification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Notification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotificationRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockNotificationRepository_Expecter) Get(ctx interface{}, id interface{}) *MockNotificationRepository_Get_Call {
	return &MockNotificationRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockNotificationRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockNotificationRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_Get_Call) Return(notification *entity.Notification, err error) *MockNotificationRepository_Get_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockNotificationRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Notification, error)) *MockNotificationRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) GetByUser(ctx context.Context, userID string, limit int, offset int) ([]*entity.Notification, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.Notification, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.Notification); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockNotificationRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) GetByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_GetByUser_Call {
	return &MockNotificationRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID, limit, offset)}
}

func (_c *MockNotificationRepository_GetByUser_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockNotificationRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_GetByUser_Call) Return(notifications []*entity.Notification, err error) *MockNotificationRepository_GetByUser_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNotificationRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int, offset int) ([]*entity.Notification, error)) *MockNotificationRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPending provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) GetPending(ctx context.Context, limit int, offset int) ([]*entity.Notification, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPending")
	}

	var r0 []*entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.Notification, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entity.Notification); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_GetPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPending'
type MockNotificationRepository_GetPending_Call struct {
	*mock.Call
}

// GetPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) GetPending(ctx interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_GetPending_Call {
	return &MockNotificationRepository_GetPending_Call{Call: _e.mock.On("GetPending", ctx, limit, offset)}
}

func (_c *MockNotificationRepository_GetPending_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockNotificationRepository_GetPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_GetPending_Call) Return(notifications []*entity.Notification, err error) *MockNotificationRepository_GetPending_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNotificationRepository_GetPending_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*entity.Notification, error)) *MockNotificationRepository_GetPending_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) List(ctx context.Context, limit int, offset int) ([]*entity.Notification, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.Notification, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entity.Notification); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_List_Call {
	return &MockNotificationRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockNotificationRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockNotificationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_List_Call) Return(notifications []*entity.Notification, err error) *MockNotificationRepository_List_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNotificationRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*entity.Notification, error)) *MockNotificationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsSent provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) MarkAsSent(ctx context.Context, id string, sentAt time.Time) error {
	ret := _mock.Called(ctx, id, sentAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsSent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, sentAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_MarkAsSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsSent'
type MockNotificationRepository_MarkAsSent_Call struct {
	*mock.Call
}

// MarkAsSent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - sentAt time.Time
func (_e *MockNotificationRepository_Expecter) MarkAsSent(ctx interface{}, id interface{}, sentAt interface{}) *MockNotificationRepository_MarkAsSent_Call {
	return &MockNotificationRepository_MarkAsSent_Call{Call: _e.mock.On("MarkAsSent", ctx, id, sentAt)}
}

func (_c *MockNotificationRepository_MarkAsSent_Call) Run(run func(ctx context.Context, id string, sentAt time.Time)) *MockNotificationRepository_MarkAsSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAsSent_Call) Return(err error) *MockNotificationRepository_MarkAsSent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_MarkAsSent_Call) RunAndReturn(run func(ctx context.Context, id string, sentAt time.Time) error) *MockNotificationRepository_MarkAsSent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockNotificationRepository
func (_mock *MockNotificationRepository) UpdateStatus(ctx context.Context, id string, status entity.NotificationStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.NotificationStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockNotificationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status entity.NotificationStatus
func (_e *MockNotificationRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockNotificationRepository_UpdateStatus_Call {
	return &MockNotificationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockNotificationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status entity.NotificationStatus)) *MockNotificationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.NotificationStatus
		if args[2] != nil {
			arg2 = args[2].(entity.NotificationStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationRepository_UpdateStatus_Call) Return(err error) *MockNotificationRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status entity.NotificationStatus) error) *MockNotificationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
