// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockIssuanceRepository is an autogenerated mock type for the IssuanceRepository type
type MockIssuanceRepository struct {
	mock.Mock
}

type MockIssuanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssuanceRepository) EXPECT() *MockIssuanceRepository_Expecter {
	return &MockIssuanceRepository_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, order, tickets, settlement
func (_m *MockIssuanceRepository) Issue(ctx context.Context, order *entity.Order, tickets []*entity.Ticket, settlement *entity.Settlement) error {
	ret := _m.Called(ctx, order, tickets, settlement)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Order, []*entity.Ticket, *entity.Settlement) error); ok {
		r0 = rf(ctx, order, tickets, settlement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIssuanceRepository_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockIssuanceRepository_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
//   - tickets []*entity.Ticket
//   - settlement *entity.Settlement
func (_e *MockIssuanceRepository_Expecter) Issue(ctx interface{}, order interface{}, tickets interface{}, settlement interface{}) *MockIssuanceRepository_Issue_Call {
	return &MockIssuanceRepository_Issue_Call{Call: _e.mock.On("Issue", ctx, order, tickets, settlement)}
}

func (_c *MockIssuanceRepository_Issue_Call) Run(run func(ctx context.Context, order *entity.Order, tickets []*entity.Ticket, settlement *entity.Settlement)) *MockIssuanceRepository_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Order), args[2].([]*entity.Ticket), args[3].(*entity.Settlement))
	})
	return _c
}

func (_c *MockIssuanceRepository_Issue_Call) Return(_a0 error) *MockIssuanceRepository_Issue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIssuanceRepository_Issue_Call) RunAndReturn(run func(context.Context, *entity.Order, []*entity.Ticket, *entity.Settlement) error) *MockIssuanceRepository_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplicationIDsAwaitingIssuance provides a mock function with given fields: ctx
func (_m *MockIssuanceRepository) ListApplicationIDsAwaitingIssuance(ctx context.Context) ([]entity.TicketApplicationID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListApplicationIDsAwaitingIssuance")
	}

	var r0 []entity.TicketApplicationID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.TicketApplicationID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.TicketApplicationID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TicketApplicationID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplicationIDsAwaitingIssuance'
type MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call struct {
	*mock.Call
}

// ListApplicationIDsAwaitingIssuance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIssuanceRepository_Expecter) ListApplicationIDsAwaitingIssuance(ctx interface{}) *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call {
	return &MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call{Call: _e.mock.On("ListApplicationIDsAwaitingIssuance", ctx)}
}

func (_c *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call) Run(run func(ctx context.Context)) *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call) Return(_a0 []entity.TicketApplicationID, _a1 error) *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call) RunAndReturn(run func(context.Context) ([]entity.TicketApplicationID, error)) *MockIssuanceRepository_ListApplicationIDsAwaitingIssuance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuanceRepository creates a new instance of MockIssuanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuanceRepository {
	mock := &MockIssuanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
