// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockOrderRepository) Get(ctx context.Context, id entity.OrderID) (*entity.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderID) (*entity.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderID) *entity.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.OrderID
func (_e *MockOrderRepository_Expecter) Get(ctx interface{}, id interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(ctx context.Context, id entity.OrderID)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.OrderID))
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(context.Context, entity.OrderID) (*entity.Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByApplicationID provides a mock function with given fields: ctx, applicationID
func (_m *MockOrderRepository) GetByApplicationID(ctx context.Context, applicationID entity.TicketApplicationID) (*entity.Order, error) {
	ret := _m.Called(ctx, applicationID)

	if len(ret) == 0 {
		panic("no return value specified for GetByApplicationID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketApplicationID) (*entity.Order, error)); ok {
		return rf(ctx, applicationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TicketApplicationID) *entity.Order); ok {
		r0 = rf(ctx, applicationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TicketApplicationID) error); ok {
		r1 = rf(ctx, applicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByApplicationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByApplicationID'
type MockOrderRepository_GetByApplicationID_Call struct {
	*mock.Call
}

// GetByApplicationID is a helper method to define mock.On call
//   - ctx context.Context
//   - applicationID entity.TicketApplicationID
func (_e *MockOrderRepository_Expecter) GetByApplicationID(ctx interface{}, applicationID interface{}) *MockOrderRepository_GetByApplicationID_Call {
	return &MockOrderRepository_GetByApplicationID_Call{Call: _e.mock.On("GetByApplicationID", ctx, applicationID)}
}

func (_c *MockOrderRepository_GetByApplicationID_Call) Run(run func(ctx context.Context, applicationID entity.TicketApplicationID)) *MockOrderRepository_GetByApplicationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TicketApplicationID))
	})
	return _c
}

func (_c *MockOrderRepository_GetByApplicationID_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderRepository_GetByApplicationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByApplicationID_Call) RunAndReturn(run func(context.Context, entity.TicketApplicationID) (*entity.Order, error)) *MockOrderRepository_GetByApplicationID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPaymentIntentRef provides a mock function with given fields: ctx, paymentIntentRef
func (_m *MockOrderRepository) GetByPaymentIntentRef(ctx context.Context, paymentIntentRef string) (*entity.Order, error) {
	ret := _m.Called(ctx, paymentIntentRef)

	if len(ret) == 0 {
		panic("no return value specified for GetByPaymentIntentRef")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Order, error)); ok {
		return rf(ctx, paymentIntentRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Order); ok {
		r0 = rf(ctx, paymentIntentRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentIntentRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetByPaymentIntentRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPaymentIntentRef'
type MockOrderRepository_GetByPaymentIntentRef_Call struct {
	*mock.Call
}

// GetByPaymentIntentRef is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentRef string
func (_e *MockOrderRepository_Expecter) GetByPaymentIntentRef(ctx interface{}, paymentIntentRef interface{}) *MockOrderRepository_GetByPaymentIntentRef_Call {
	return &MockOrderRepository_GetByPaymentIntentRef_Call{Call: _e.mock.On("GetByPaymentIntentRef", ctx, paymentIntentRef)}
}

func (_c *MockOrderRepository_GetByPaymentIntentRef_Call) Run(run func(ctx context.Context, paymentIntentRef string)) *MockOrderRepository_GetByPaymentIntentRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderRepository_GetByPaymentIntentRef_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderRepository_GetByPaymentIntentRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetByPaymentIntentRef_Call) RunAndReturn(run func(context.Context, string) (*entity.Order, error)) *MockOrderRepository_GetByPaymentIntentRef_Call {
	_c.Call.Return(run)
	return _c
}

// ListByBuyer provides a mock function with given fields: ctx, buyerID
func (_m *MockOrderRepository) ListByBuyer(ctx context.Context, buyerID entity.UserID) ([]*entity.Order, error) {
	ret := _m.Called(ctx, buyerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByBuyer")
	}

	var r0 []*entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID) ([]*entity.Order, error)); ok {
		return rf(ctx, buyerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID) []*entity.Order); ok {
		r0 = rf(ctx, buyerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID) error); ok {
		r1 = rf(ctx, buyerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListByBuyer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByBuyer'
type MockOrderRepository_ListByBuyer_Call struct {
	*mock.Call
}

// ListByBuyer is a helper method to define mock.On call
//   - ctx context.Context
//   - buyerID entity.UserID
func (_e *MockOrderRepository_Expecter) ListByBuyer(ctx interface{}, buyerID interface{}) *MockOrderRepository_ListByBuyer_Call {
	return &MockOrderRepository_ListByBuyer_Call{Call: _e.mock.On("ListByBuyer", ctx, buyerID)}
}

func (_c *MockOrderRepository_ListByBuyer_Call) Run(run func(ctx context.Context, buyerID entity.UserID)) *MockOrderRepository_ListByBuyer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID))
	})
	return _c
}

func (_c *MockOrderRepository_ListByBuyer_Call) Return(_a0 []*entity.Order, _a1 error) *MockOrderRepository_ListByBuyer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListByBuyer_Call) RunAndReturn(run func(context.Context, entity.UserID) ([]*entity.Order, error)) *MockOrderRepository_ListByBuyer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockOrderRepository) UpdateStatus(ctx context.Context, id entity.OrderID, status entity.OrderStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderID, entity.OrderStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id entity.OrderID
//   - status entity.OrderStatus
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id entity.OrderID, status entity.OrderStatus)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.OrderID), args[2].(entity.OrderStatus))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(_a0 error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, entity.OrderID, entity.OrderStatus) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
