// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSalesPhaseRepository is an autogenerated mock type for the SalesPhaseRepository type
type MockSalesPhaseRepository struct {
	mock.Mock
}

type MockSalesPhaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalesPhaseRepository) EXPECT() *MockSalesPhaseRepository_Expecter {
	return &MockSalesPhaseRepository_Expecter{mock: &_m.Mock}
}

// GetBySeries provides a mock function with given fields: ctx, seriesID
func (_m *MockSalesPhaseRepository) GetBySeries(ctx context.Context, seriesID string) ([]*entity.SalesPhase, error) {
	ret := _m.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySeries")
	}

	var r0 []*entity.SalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.SalesPhase, error)); ok {
		return rf(ctx, seriesID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.SalesPhase); ok {
		r0 = rf(ctx, seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, seriesID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSalesPhaseRepository_GetBySeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySeries'
type MockSalesPhaseRepository_GetBySeries_Call struct {
	*mock.Call
}

// GetBySeries is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID string
func (_e *MockSalesPhaseRepository_Expecter) GetBySeries(ctx interface{}, seriesID interface{}) *MockSalesPhaseRepository_GetBySeries_Call {
	return &MockSalesPhaseRepository_GetBySeries_Call{Call: _e.mock.On("GetBySeries", ctx, seriesID)}
}

func (_c *MockSalesPhaseRepository_GetBySeries_Call) Run(run func(ctx context.Context, seriesID string)) *MockSalesPhaseRepository_GetBySeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSalesPhaseRepository_GetBySeries_Call) Return(_a0 []*entity.SalesPhase, _a1 error) *MockSalesPhaseRepository_GetBySeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSalesPhaseRepository_GetBySeries_Call) RunAndReturn(run func(context.Context, string) ([]*entity.SalesPhase, error)) *MockSalesPhaseRepository_GetBySeries_Call {
	_c.Call.Return(run)
	return _c
}

// ListPhasesWithPendingMilestones provides a mock function with given fields: ctx, lookahead, lookbackMargin
func (_m *MockSalesPhaseRepository) ListPhasesWithPendingMilestones(ctx context.Context, lookahead time.Duration, lookbackMargin time.Duration) ([]*entity.SalesPhase, error) {
	ret := _m.Called(ctx, lookahead, lookbackMargin)

	if len(ret) == 0 {
		panic("no return value specified for ListPhasesWithPendingMilestones")
	}

	var r0 []*entity.SalesPhase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, time.Duration) ([]*entity.SalesPhase, error)); ok {
		return rf(ctx, lookahead, lookbackMargin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, time.Duration) []*entity.SalesPhase); ok {
		r0 = rf(ctx, lookahead, lookbackMargin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SalesPhase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration, time.Duration) error); ok {
		r1 = rf(ctx, lookahead, lookbackMargin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPhasesWithPendingMilestones'
type MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call struct {
	*mock.Call
}

// ListPhasesWithPendingMilestones is a helper method to define mock.On call
//   - ctx context.Context
//   - lookahead time.Duration
//   - lookbackMargin time.Duration
func (_e *MockSalesPhaseRepository_Expecter) ListPhasesWithPendingMilestones(ctx interface{}, lookahead interface{}, lookbackMargin interface{}) *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call {
	return &MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call{Call: _e.mock.On("ListPhasesWithPendingMilestones", ctx, lookahead, lookbackMargin)}
}

func (_c *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call) Run(run func(ctx context.Context, lookahead time.Duration, lookbackMargin time.Duration)) *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call) Return(_a0 []*entity.SalesPhase, _a1 error) *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call) RunAndReturn(run func(context.Context, time.Duration, time.Duration) ([]*entity.SalesPhase, error)) *MockSalesPhaseRepository_ListPhasesWithPendingMilestones_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceCoveredEvents provides a mock function with given fields: ctx, phaseID, eventIDs
func (_m *MockSalesPhaseRepository) ReplaceCoveredEvents(ctx context.Context, phaseID string, eventIDs []string) error {
	ret := _m.Called(ctx, phaseID, eventIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceCoveredEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, phaseID, eventIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSalesPhaseRepository_ReplaceCoveredEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceCoveredEvents'
type MockSalesPhaseRepository_ReplaceCoveredEvents_Call struct {
	*mock.Call
}

// ReplaceCoveredEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - phaseID string
//   - eventIDs []string
func (_e *MockSalesPhaseRepository_Expecter) ReplaceCoveredEvents(ctx interface{}, phaseID interface{}, eventIDs interface{}) *MockSalesPhaseRepository_ReplaceCoveredEvents_Call {
	return &MockSalesPhaseRepository_ReplaceCoveredEvents_Call{Call: _e.mock.On("ReplaceCoveredEvents", ctx, phaseID, eventIDs)}
}

func (_c *MockSalesPhaseRepository_ReplaceCoveredEvents_Call) Run(run func(ctx context.Context, phaseID string, eventIDs []string)) *MockSalesPhaseRepository_ReplaceCoveredEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockSalesPhaseRepository_ReplaceCoveredEvents_Call) Return(_a0 error) *MockSalesPhaseRepository_ReplaceCoveredEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSalesPhaseRepository_ReplaceCoveredEvents_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockSalesPhaseRepository_ReplaceCoveredEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, candidate
func (_m *MockSalesPhaseRepository) Upsert(ctx context.Context, candidate *entity.SalesPhaseCandidate) (string, entity.UpsertOutcome, error) {
	ret := _m.Called(ctx, candidate)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 string
	var r1 entity.UpsertOutcome
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SalesPhaseCandidate) (string, entity.UpsertOutcome, error)); ok {
		return rf(ctx, candidate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SalesPhaseCandidate) string); ok {
		r0 = rf(ctx, candidate)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SalesPhaseCandidate) entity.UpsertOutcome); ok {
		r1 = rf(ctx, candidate)
	} else {
		r1 = ret.Get(1).(entity.UpsertOutcome)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *entity.SalesPhaseCandidate) error); ok {
		r2 = rf(ctx, candidate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSalesPhaseRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSalesPhaseRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - candidate *entity.SalesPhaseCandidate
func (_e *MockSalesPhaseRepository_Expecter) Upsert(ctx interface{}, candidate interface{}) *MockSalesPhaseRepository_Upsert_Call {
	return &MockSalesPhaseRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, candidate)}
}

func (_c *MockSalesPhaseRepository_Upsert_Call) Run(run func(ctx context.Context, candidate *entity.SalesPhaseCandidate)) *MockSalesPhaseRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SalesPhaseCandidate))
	})
	return _c
}

func (_c *MockSalesPhaseRepository_Upsert_Call) Return(_a0 string, _a1 entity.UpsertOutcome, _a2 error) *MockSalesPhaseRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSalesPhaseRepository_Upsert_Call) RunAndReturn(run func(context.Context, *entity.SalesPhaseCandidate) (string, entity.UpsertOutcome, error)) *MockSalesPhaseRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalesPhaseRepository creates a new instance of MockSalesPhaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalesPhaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalesPhaseRepository {
	mock := &MockSalesPhaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
