// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentAuthorizationPort is an autogenerated mock type for the PaymentAuthorizationPort type
type MockPaymentAuthorizationPort struct {
	mock.Mock
}

type MockPaymentAuthorizationPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentAuthorizationPort) EXPECT() *MockPaymentAuthorizationPort_Expecter {
	return &MockPaymentAuthorizationPort_Expecter{mock: &_m.Mock}
}

// CancelAuthorization provides a mock function with given fields: ctx, paymentIntentRef
func (_m *MockPaymentAuthorizationPort) CancelAuthorization(ctx context.Context, paymentIntentRef string) error {
	ret := _m.Called(ctx, paymentIntentRef)

	if len(ret) == 0 {
		panic("no return value specified for CancelAuthorization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, paymentIntentRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentAuthorizationPort_CancelAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAuthorization'
type MockPaymentAuthorizationPort_CancelAuthorization_Call struct {
	*mock.Call
}

// CancelAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentRef string
func (_e *MockPaymentAuthorizationPort_Expecter) CancelAuthorization(ctx interface{}, paymentIntentRef interface{}) *MockPaymentAuthorizationPort_CancelAuthorization_Call {
	return &MockPaymentAuthorizationPort_CancelAuthorization_Call{Call: _e.mock.On("CancelAuthorization", ctx, paymentIntentRef)}
}

func (_c *MockPaymentAuthorizationPort_CancelAuthorization_Call) Run(run func(ctx context.Context, paymentIntentRef string)) *MockPaymentAuthorizationPort_CancelAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentAuthorizationPort_CancelAuthorization_Call) Return(_a0 error) *MockPaymentAuthorizationPort_CancelAuthorization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentAuthorizationPort_CancelAuthorization_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentAuthorizationPort_CancelAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// CaptureAuthorization provides a mock function with given fields: ctx, paymentIntentRef
func (_m *MockPaymentAuthorizationPort) CaptureAuthorization(ctx context.Context, paymentIntentRef string) error {
	ret := _m.Called(ctx, paymentIntentRef)

	if len(ret) == 0 {
		panic("no return value specified for CaptureAuthorization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, paymentIntentRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentAuthorizationPort_CaptureAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureAuthorization'
type MockPaymentAuthorizationPort_CaptureAuthorization_Call struct {
	*mock.Call
}

// CaptureAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentRef string
func (_e *MockPaymentAuthorizationPort_Expecter) CaptureAuthorization(ctx interface{}, paymentIntentRef interface{}) *MockPaymentAuthorizationPort_CaptureAuthorization_Call {
	return &MockPaymentAuthorizationPort_CaptureAuthorization_Call{Call: _e.mock.On("CaptureAuthorization", ctx, paymentIntentRef)}
}

func (_c *MockPaymentAuthorizationPort_CaptureAuthorization_Call) Run(run func(ctx context.Context, paymentIntentRef string)) *MockPaymentAuthorizationPort_CaptureAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentAuthorizationPort_CaptureAuthorization_Call) Return(_a0 error) *MockPaymentAuthorizationPort_CaptureAuthorization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentAuthorizationPort_CaptureAuthorization_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentAuthorizationPort_CaptureAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuthorization provides a mock function with given fields: ctx, amountJPY
func (_m *MockPaymentAuthorizationPort) CreateAuthorization(ctx context.Context, amountJPY int64) (string, string, error) {
	ret := _m.Called(ctx, amountJPY)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthorization")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (string, string, error)); ok {
		return rf(ctx, amountJPY)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, amountJPY)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) string); ok {
		r1 = rf(ctx, amountJPY)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, amountJPY)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPaymentAuthorizationPort_CreateAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthorization'
type MockPaymentAuthorizationPort_CreateAuthorization_Call struct {
	*mock.Call
}

// CreateAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - amountJPY int64
func (_e *MockPaymentAuthorizationPort_Expecter) CreateAuthorization(ctx interface{}, amountJPY interface{}) *MockPaymentAuthorizationPort_CreateAuthorization_Call {
	return &MockPaymentAuthorizationPort_CreateAuthorization_Call{Call: _e.mock.On("CreateAuthorization", ctx, amountJPY)}
}

func (_c *MockPaymentAuthorizationPort_CreateAuthorization_Call) Run(run func(ctx context.Context, amountJPY int64)) *MockPaymentAuthorizationPort_CreateAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPaymentAuthorizationPort_CreateAuthorization_Call) Return(paymentIntentRef string, clientSecret string, err error) *MockPaymentAuthorizationPort_CreateAuthorization_Call {
	_c.Call.Return(paymentIntentRef, clientSecret, err)
	return _c
}

func (_c *MockPaymentAuthorizationPort_CreateAuthorization_Call) RunAndReturn(run func(context.Context, int64) (string, string, error)) *MockPaymentAuthorizationPort_CreateAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAuthorization provides a mock function with given fields: ctx, paymentIntentRef, expectedAmountJPY
func (_m *MockPaymentAuthorizationPort) VerifyAuthorization(ctx context.Context, paymentIntentRef string, expectedAmountJPY int64) error {
	ret := _m.Called(ctx, paymentIntentRef, expectedAmountJPY)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAuthorization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, paymentIntentRef, expectedAmountJPY)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentAuthorizationPort_VerifyAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAuthorization'
type MockPaymentAuthorizationPort_VerifyAuthorization_Call struct {
	*mock.Call
}

// VerifyAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentIntentRef string
//   - expectedAmountJPY int64
func (_e *MockPaymentAuthorizationPort_Expecter) VerifyAuthorization(ctx interface{}, paymentIntentRef interface{}, expectedAmountJPY interface{}) *MockPaymentAuthorizationPort_VerifyAuthorization_Call {
	return &MockPaymentAuthorizationPort_VerifyAuthorization_Call{Call: _e.mock.On("VerifyAuthorization", ctx, paymentIntentRef, expectedAmountJPY)}
}

func (_c *MockPaymentAuthorizationPort_VerifyAuthorization_Call) Run(run func(ctx context.Context, paymentIntentRef string, expectedAmountJPY int64)) *MockPaymentAuthorizationPort_VerifyAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockPaymentAuthorizationPort_VerifyAuthorization_Call) Return(_a0 error) *MockPaymentAuthorizationPort_VerifyAuthorization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentAuthorizationPort_VerifyAuthorization_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockPaymentAuthorizationPort_VerifyAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentAuthorizationPort creates a new instance of MockPaymentAuthorizationPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentAuthorizationPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentAuthorizationPort {
	mock := &MockPaymentAuthorizationPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
