// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockArtistImageResolver is an autogenerated mock type for the ArtistImageResolver type
type MockArtistImageResolver struct {
	mock.Mock
}

type MockArtistImageResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistImageResolver) EXPECT() *MockArtistImageResolver_Expecter {
	return &MockArtistImageResolver_Expecter{mock: &_m.Mock}
}

// ResolveImages provides a mock function with given fields: ctx, mbid
func (_m *MockArtistImageResolver) ResolveImages(ctx context.Context, mbid string) (*entity.Fanart, error) {
	ret := _m.Called(ctx, mbid)

	if len(ret) == 0 {
		panic("no return value specified for ResolveImages")
	}

	var r0 *entity.Fanart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Fanart, error)); ok {
		return rf(ctx, mbid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Fanart); ok {
		r0 = rf(ctx, mbid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Fanart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mbid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistImageResolver_ResolveImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveImages'
type MockArtistImageResolver_ResolveImages_Call struct {
	*mock.Call
}

// ResolveImages is a helper method to define mock.On call
//   - ctx context.Context
//   - mbid string
func (_e *MockArtistImageResolver_Expecter) ResolveImages(ctx interface{}, mbid interface{}) *MockArtistImageResolver_ResolveImages_Call {
	return &MockArtistImageResolver_ResolveImages_Call{Call: _e.mock.On("ResolveImages", ctx, mbid)}
}

func (_c *MockArtistImageResolver_ResolveImages_Call) Run(run func(ctx context.Context, mbid string)) *MockArtistImageResolver_ResolveImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArtistImageResolver_ResolveImages_Call) Return(_a0 *entity.Fanart, _a1 error) *MockArtistImageResolver_ResolveImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistImageResolver_ResolveImages_Call) RunAndReturn(run func(context.Context, string) (*entity.Fanart, error)) *MockArtistImageResolver_ResolveImages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArtistImageResolver creates a new instance of MockArtistImageResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistImageResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistImageResolver {
	mock := &MockArtistImageResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
