version: '2'

run:
  timeout: 3m
  go: '1.24'
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - revive  # Enable revive for code quality checks

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"  # Check receiver names
          - "sayRepetitiveInsteadOfStutters"  # Better error messages
