version: '2'

run:
  timeout: 3m
  go: '1.25'
  modules-download-mode: readonly

linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
