with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/liverty-music/backend/internal/usecase:
    interfaces:
      ArtistUseCase:
      ConcertUseCase:
      UserUseCase:
      TicketUseCase:
  github.com/liverty-music/backend/internal/entity:
    interfaces:
      ArtistRepository:
      ConcertRepository:
      ConcertSearcher:
      NotificationRepository:
      UserRepository:
      UserArtistSubscriptionRepository:
      SearchLogRepository:
      VenueRepository:
      TicketMinter:
      TicketRepository:
  github.com/liverty-music/backend/internal/infrastructure/auth:
    interfaces:
      TokenValidator:
