with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/liverty-music/backend/internal/usecase:
    interfaces:
      ArtistUseCase:
      ConcertUseCase:
      UserUseCase:
  github.com/liverty-music/backend/internal/entity:
    interfaces:
      ArtistRepository:
      ConcertRepository:
      ConcertSearcher:
      NotificationRepository:
      UserRepository:
      UserArtistSubscriptionRepository:
      VenueRepository:
