// Package entity defines core domain entities and business logic interfaces.
package entity

import "context"

// PushSubscription represents a browser Web Push API subscription registered by a user.
//
// Each record stores the cryptographic material required to encrypt and deliver
// a push message to a specific browser session. A single user may hold multiple
// subscriptions (one per active browser session).
type PushSubscription struct {
	// ID is the unique internal identifier for the subscription (UUIDv7).
	ID string
	// UserID is the foreign key reference to the [User] who owns this subscription.
	UserID string
	// Endpoint is the push service URL provided by the browser's PushManager API.
	// It uniquely identifies the browser session at the push service.
	Endpoint string
	// P256dh is the Base64url-encoded ECDH public key generated by the browser.
	// The server uses it to encrypt notification payloads.
	P256dh string
	// Auth is the Base64url-encoded authentication secret generated by the browser.
	// Together with P256dh, it forms the cryptographic material for payload encryption.
	Auth string
}

// PushSubscriptionRepository defines the persistence layer operations for push subscription entities.
//
// All mutation and single-subscription retrieval operations are scoped to the
// (userID, endpoint) pair so each call affects exactly one browser session.
type PushSubscriptionRepository interface {
	// Create persists a new push subscription, or updates the existing record
	// when the endpoint is already registered (UPSERT by endpoint).
	//
	// # Possible errors:
	//
	//   - Internal: database connection or execution failure.
	Create(ctx context.Context, sub *PushSubscription) error

	// Get retrieves the push subscription uniquely identified by the (userID, endpoint) pair.
	//
	// # Possible errors:
	//
	//   - NotFound: no subscription matches the supplied (userID, endpoint) pair.
	//   - Internal: database query failure.
	Get(ctx context.Context, userID, endpoint string) (*PushSubscription, error)

	// Delete removes the push subscription uniquely identified by the (userID, endpoint)
	// pair. Only the specified browser's row is deleted; other browsers registered
	// by the same user remain active. Deleting a subscription that does not exist
	// returns a successful nil result (idempotency).
	//
	// # Possible errors:
	//
	//   - Internal: database execution failure.
	Delete(ctx context.Context, userID, endpoint string) error

	// ListByUserIDs retrieves all push subscriptions belonging to any of the given user IDs.
	// Returns an empty slice (no error) when none of the users have registered subscriptions.
	//
	// Used only by the internal push delivery path; not exposed via RPC.
	//
	// # Possible errors:
	//
	//   - Internal: database query failure.
	ListByUserIDs(ctx context.Context, userIDs []string) ([]*PushSubscription, error)
}
