// Package entity defines core domain entities and business logic interfaces.
package entity

import "context"

// PushSubscription represents a browser Web Push API subscription registered by a user.
//
// Each record stores the cryptographic material required to encrypt and deliver
// a push message to a specific browser session. A single user may hold multiple
// subscriptions (one per active browser session).
type PushSubscription struct {
	// ID is the unique internal identifier for the subscription (UUIDv7).
	ID string
	// UserID is the foreign key reference to the [User] who owns this subscription.
	UserID string
	// Endpoint is the push service URL provided by the browser's PushManager API.
	// It uniquely identifies the browser session at the push service.
	Endpoint string
	// P256dh is the Base64url-encoded ECDH public key generated by the browser.
	// The server uses it to encrypt notification payloads.
	P256dh string
	// Auth is the Base64url-encoded authentication secret generated by the browser.
	// Together with P256dh, it forms the cryptographic material for payload encryption.
	Auth string
}

// PushSubscriptionRepository defines the persistence layer operations for push subscription entities.
type PushSubscriptionRepository interface {
	// Create persists a new push subscription, or updates the existing record
	// when the endpoint is already registered (UPSERT by endpoint).
	//
	// # Possible errors:
	//
	//   - Internal: database connection or execution failure.
	Create(ctx context.Context, sub *PushSubscription) error

	// DeleteByEndpoint removes the push subscription identified by the given endpoint URL.
	//
	// # Possible errors:
	//
	//   - Internal: database execution failure.
	DeleteByEndpoint(ctx context.Context, endpoint string) error

	// ListByUserIDs retrieves all push subscriptions belonging to any of the given user IDs.
	// Returns an empty slice (no error) when none of the users have registered subscriptions.
	//
	// # Possible errors:
	//
	//   - Internal: database query failure.
	ListByUserIDs(ctx context.Context, userIDs []string) ([]*PushSubscription, error)

	// DeleteByUserID removes all push subscriptions associated with the given user.
	// This operation is idempotent: it succeeds even if the user has no subscriptions.
	//
	// # Possible errors:
	//
	//   - Internal: database execution failure.
	DeleteByUserID(ctx context.Context, userID string) error
}
