// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAnalyticsConsumerMetrics is an autogenerated mock type for the AnalyticsConsumerMetrics type
type MockAnalyticsConsumerMetrics struct {
	mock.Mock
}

type MockAnalyticsConsumerMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsConsumerMetrics) EXPECT() *MockAnalyticsConsumerMetrics_Expecter {
	return &MockAnalyticsConsumerMetrics_Expecter{mock: &_m.Mock}
}

// RecordLag provides a mock function with given fields: ctx, seconds
func (_m *MockAnalyticsConsumerMetrics) RecordLag(ctx context.Context, seconds float64) {
	_m.Called(ctx, seconds)
}

// MockAnalyticsConsumerMetrics_RecordLag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordLag'
type MockAnalyticsConsumerMetrics_RecordLag_Call struct {
	*mock.Call
}

// RecordLag is a helper method to define mock.On call
//   - ctx context.Context
//   - seconds float64
func (_e *MockAnalyticsConsumerMetrics_Expecter) RecordLag(ctx interface{}, seconds interface{}) *MockAnalyticsConsumerMetrics_RecordLag_Call {
	return &MockAnalyticsConsumerMetrics_RecordLag_Call{Call: _e.mock.On("RecordLag", ctx, seconds)}
}

func (_c *MockAnalyticsConsumerMetrics_RecordLag_Call) Run(run func(ctx context.Context, seconds float64)) *MockAnalyticsConsumerMetrics_RecordLag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64))
	})
	return _c
}

func (_c *MockAnalyticsConsumerMetrics_RecordLag_Call) Return() *MockAnalyticsConsumerMetrics_RecordLag_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsConsumerMetrics_RecordLag_Call) RunAndReturn(run func(context.Context, float64)) *MockAnalyticsConsumerMetrics_RecordLag_Call {
	_c.Run(run)
	return _c
}

// RecordMessage provides a mock function with given fields: ctx, status
func (_m *MockAnalyticsConsumerMetrics) RecordMessage(ctx context.Context, status string) {
	_m.Called(ctx, status)
}

// MockAnalyticsConsumerMetrics_RecordMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordMessage'
type MockAnalyticsConsumerMetrics_RecordMessage_Call struct {
	*mock.Call
}

// RecordMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockAnalyticsConsumerMetrics_Expecter) RecordMessage(ctx interface{}, status interface{}) *MockAnalyticsConsumerMetrics_RecordMessage_Call {
	return &MockAnalyticsConsumerMetrics_RecordMessage_Call{Call: _e.mock.On("RecordMessage", ctx, status)}
}

func (_c *MockAnalyticsConsumerMetrics_RecordMessage_Call) Run(run func(ctx context.Context, status string)) *MockAnalyticsConsumerMetrics_RecordMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAnalyticsConsumerMetrics_RecordMessage_Call) Return() *MockAnalyticsConsumerMetrics_RecordMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsConsumerMetrics_RecordMessage_Call) RunAndReturn(run func(context.Context, string)) *MockAnalyticsConsumerMetrics_RecordMessage_Call {
	_c.Run(run)
	return _c
}

// NewMockAnalyticsConsumerMetrics creates a new instance of MockAnalyticsConsumerMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsConsumerMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsConsumerMetrics {
	mock := &MockAnalyticsConsumerMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
