// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockSalesReminderDeliveryUseCase is an autogenerated mock type for the SalesReminderDeliveryUseCase type
type MockSalesReminderDeliveryUseCase struct {
	mock.Mock
}

type MockSalesReminderDeliveryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalesReminderDeliveryUseCase) EXPECT() *MockSalesReminderDeliveryUseCase_Expecter {
	return &MockSalesReminderDeliveryUseCase_Expecter{mock: &_m.Mock}
}

// DeliverReminder provides a mock function with given fields: ctx, data
func (_m *MockSalesReminderDeliveryUseCase) DeliverReminder(ctx context.Context, data entity.SalesPhaseReminderDueData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for DeliverReminder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.SalesPhaseReminderDueData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSalesReminderDeliveryUseCase_DeliverReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeliverReminder'
type MockSalesReminderDeliveryUseCase_DeliverReminder_Call struct {
	*mock.Call
}

// DeliverReminder is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.SalesPhaseReminderDueData
func (_e *MockSalesReminderDeliveryUseCase_Expecter) DeliverReminder(ctx interface{}, data interface{}) *MockSalesReminderDeliveryUseCase_DeliverReminder_Call {
	return &MockSalesReminderDeliveryUseCase_DeliverReminder_Call{Call: _e.mock.On("DeliverReminder", ctx, data)}
}

func (_c *MockSalesReminderDeliveryUseCase_DeliverReminder_Call) Run(run func(ctx context.Context, data entity.SalesPhaseReminderDueData)) *MockSalesReminderDeliveryUseCase_DeliverReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.SalesPhaseReminderDueData))
	})
	return _c
}

func (_c *MockSalesReminderDeliveryUseCase_DeliverReminder_Call) Return(_a0 error) *MockSalesReminderDeliveryUseCase_DeliverReminder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSalesReminderDeliveryUseCase_DeliverReminder_Call) RunAndReturn(run func(context.Context, entity.SalesPhaseReminderDueData) error) *MockSalesReminderDeliveryUseCase_DeliverReminder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalesReminderDeliveryUseCase creates a new instance of MockSalesReminderDeliveryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalesReminderDeliveryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalesReminderDeliveryUseCase {
	mock := &MockSalesReminderDeliveryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
