// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/liverty-music/backend/internal/usecase"
)

// MockReservationUseCase is an autogenerated mock type for the ReservationUseCase type
type MockReservationUseCase struct {
	mock.Mock
}

type MockReservationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationUseCase) EXPECT() *MockReservationUseCase_Expecter {
	return &MockReservationUseCase_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, userID, reservationID, identity
func (_m *MockReservationUseCase) Authorize(ctx context.Context, userID entity.UserID, reservationID entity.ReservationID, identity entity.HolderIdentity) (string, error) {
	ret := _m.Called(ctx, userID, reservationID, identity)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.ReservationID, entity.HolderIdentity) (string, error)); ok {
		return rf(ctx, userID, reservationID, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.ReservationID, entity.HolderIdentity) string); ok {
		r0 = rf(ctx, userID, reservationID, identity)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID, entity.ReservationID, entity.HolderIdentity) error); ok {
		r1 = rf(ctx, userID, reservationID, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationUseCase_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockReservationUseCase_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entity.UserID
//   - reservationID entity.ReservationID
//   - identity entity.HolderIdentity
func (_e *MockReservationUseCase_Expecter) Authorize(ctx interface{}, userID interface{}, reservationID interface{}, identity interface{}) *MockReservationUseCase_Authorize_Call {
	return &MockReservationUseCase_Authorize_Call{Call: _e.mock.On("Authorize", ctx, userID, reservationID, identity)}
}

func (_c *MockReservationUseCase_Authorize_Call) Run(run func(ctx context.Context, userID entity.UserID, reservationID entity.ReservationID, identity entity.HolderIdentity)) *MockReservationUseCase_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID), args[2].(entity.ReservationID), args[3].(entity.HolderIdentity))
	})
	return _c
}

func (_c *MockReservationUseCase_Authorize_Call) Return(_a0 string, _a1 error) *MockReservationUseCase_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationUseCase_Authorize_Call) RunAndReturn(run func(context.Context, entity.UserID, entity.ReservationID, entity.HolderIdentity) (string, error)) *MockReservationUseCase_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID, reservationID
func (_m *MockReservationUseCase) Get(ctx context.Context, userID entity.UserID, reservationID entity.ReservationID) (*usecase.ReservationView, error) {
	ret := _m.Called(ctx, userID, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *usecase.ReservationView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.ReservationID) (*usecase.ReservationView, error)); ok {
		return rf(ctx, userID, reservationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.ReservationID) *usecase.ReservationView); ok {
		r0 = rf(ctx, userID, reservationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.ReservationView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID, entity.ReservationID) error); ok {
		r1 = rf(ctx, userID, reservationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReservationUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entity.UserID
//   - reservationID entity.ReservationID
func (_e *MockReservationUseCase_Expecter) Get(ctx interface{}, userID interface{}, reservationID interface{}) *MockReservationUseCase_Get_Call {
	return &MockReservationUseCase_Get_Call{Call: _e.mock.On("Get", ctx, userID, reservationID)}
}

func (_c *MockReservationUseCase_Get_Call) Run(run func(ctx context.Context, userID entity.UserID, reservationID entity.ReservationID)) *MockReservationUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID), args[2].(entity.ReservationID))
	})
	return _c
}

func (_c *MockReservationUseCase_Get_Call) Return(_a0 *usecase.ReservationView, _a1 error) *MockReservationUseCase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationUseCase_Get_Call) RunAndReturn(run func(context.Context, entity.UserID, entity.ReservationID) (*usecase.ReservationView, error)) *MockReservationUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExpired provides a mock function with given fields: ctx
func (_m *MockReservationUseCase) ReleaseExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationUseCase_ReleaseExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExpired'
type MockReservationUseCase_ReleaseExpired_Call struct {
	*mock.Call
}

// ReleaseExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationUseCase_Expecter) ReleaseExpired(ctx interface{}) *MockReservationUseCase_ReleaseExpired_Call {
	return &MockReservationUseCase_ReleaseExpired_Call{Call: _e.mock.On("ReleaseExpired", ctx)}
}

func (_c *MockReservationUseCase_ReleaseExpired_Call) Run(run func(ctx context.Context)) *MockReservationUseCase_ReleaseExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReservationUseCase_ReleaseExpired_Call) Return(_a0 error) *MockReservationUseCase_ReleaseExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationUseCase_ReleaseExpired_Call) RunAndReturn(run func(context.Context) error) *MockReservationUseCase_ReleaseExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, userID, saleID, count
func (_m *MockReservationUseCase) Start(ctx context.Context, userID entity.UserID, saleID entity.TicketSaleID, count int) (*usecase.StartedReservation, error) {
	ret := _m.Called(ctx, userID, saleID, count)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *usecase.StartedReservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.TicketSaleID, int) (*usecase.StartedReservation, error)); ok {
		return rf(ctx, userID, saleID, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserID, entity.TicketSaleID, int) *usecase.StartedReservation); ok {
		r0 = rf(ctx, userID, saleID, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.StartedReservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserID, entity.TicketSaleID, int) error); ok {
		r1 = rf(ctx, userID, saleID, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationUseCase_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockReservationUseCase_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - userID entity.UserID
//   - saleID entity.TicketSaleID
//   - count int
func (_e *MockReservationUseCase_Expecter) Start(ctx interface{}, userID interface{}, saleID interface{}, count interface{}) *MockReservationUseCase_Start_Call {
	return &MockReservationUseCase_Start_Call{Call: _e.mock.On("Start", ctx, userID, saleID, count)}
}

func (_c *MockReservationUseCase_Start_Call) Run(run func(ctx context.Context, userID entity.UserID, saleID entity.TicketSaleID, count int)) *MockReservationUseCase_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.UserID), args[2].(entity.TicketSaleID), args[3].(int))
	})
	return _c
}

func (_c *MockReservationUseCase_Start_Call) Return(_a0 *usecase.StartedReservation, _a1 error) *MockReservationUseCase_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationUseCase_Start_Call) RunAndReturn(run func(context.Context, entity.UserID, entity.TicketSaleID, int) (*usecase.StartedReservation, error)) *MockReservationUseCase_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReservationUseCase creates a new instance of MockReservationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationUseCase {
	mock := &MockReservationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
