// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockArtistUseCase is an autogenerated mock type for the ArtistUseCase type
type MockArtistUseCase struct {
	mock.Mock
}

type MockArtistUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistUseCase) EXPECT() *MockArtistUseCase_Expecter {
	return &MockArtistUseCase_Expecter{mock: &_m.Mock}
}

// AddMedia provides a mock function with given fields: ctx, media
func (_m *MockArtistUseCase) AddMedia(ctx context.Context, media *entity.Media) error {
	ret := _m.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for AddMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Media) error); ok {
		r0 = rf(ctx, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArtistUseCase_AddMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMedia'
type MockArtistUseCase_AddMedia_Call struct {
	*mock.Call
}

// AddMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - media *entity.Media
func (_e *MockArtistUseCase_Expecter) AddMedia(ctx interface{}, media interface{}) *MockArtistUseCase_AddMedia_Call {
	return &MockArtistUseCase_AddMedia_Call{Call: _e.mock.On("AddMedia", ctx, media)}
}

func (_c *MockArtistUseCase_AddMedia_Call) Run(run func(ctx context.Context, media *entity.Media)) *MockArtistUseCase_AddMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Media))
	})
	return _c
}

func (_c *MockArtistUseCase_AddMedia_Call) Return(_a0 error) *MockArtistUseCase_AddMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArtistUseCase_AddMedia_Call) RunAndReturn(run func(context.Context, *entity.Media) error) *MockArtistUseCase_AddMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, artist
func (_m *MockArtistUseCase) Create(ctx context.Context, artist *entity.Artist) (*entity.Artist, error) {
	ret := _m.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist) (*entity.Artist, error)); ok {
		return rf(ctx, artist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist) *entity.Artist); ok {
		r0 = rf(ctx, artist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Artist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Artist) error); ok {
		r1 = rf(ctx, artist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArtistUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
func (_e *MockArtistUseCase_Expecter) Create(ctx interface{}, artist interface{}) *MockArtistUseCase_Create_Call {
	return &MockArtistUseCase_Create_Call{Call: _e.mock.On("Create", ctx, artist)}
}

func (_c *MockArtistUseCase_Create_Call) Run(run func(ctx context.Context, artist *entity.Artist)) *MockArtistUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Artist))
	})
	return _c
}

func (_c *MockArtistUseCase_Create_Call) Return(_a0 *entity.Artist, _a1 error) *MockArtistUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistUseCase_Create_Call) RunAndReturn(run func(context.Context, *entity.Artist) (*entity.Artist, error)) *MockArtistUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMedia provides a mock function with given fields: ctx, mediaID
func (_m *MockArtistUseCase) DeleteMedia(ctx context.Context, mediaID string) error {
	ret := _m.Called(ctx, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, mediaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArtistUseCase_DeleteMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMedia'
type MockArtistUseCase_DeleteMedia_Call struct {
	*mock.Call
}

// DeleteMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaID string
func (_e *MockArtistUseCase_Expecter) DeleteMedia(ctx interface{}, mediaID interface{}) *MockArtistUseCase_DeleteMedia_Call {
	return &MockArtistUseCase_DeleteMedia_Call{Call: _e.mock.On("DeleteMedia", ctx, mediaID)}
}

func (_c *MockArtistUseCase_DeleteMedia_Call) Run(run func(ctx context.Context, mediaID string)) *MockArtistUseCase_DeleteMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArtistUseCase_DeleteMedia_Call) Return(_a0 error) *MockArtistUseCase_DeleteMedia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArtistUseCase_DeleteMedia_Call) RunAndReturn(run func(context.Context, string) error) *MockArtistUseCase_DeleteMedia_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockArtistUseCase) List(ctx context.Context) ([]*entity.Artist, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Artist, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Artist); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockArtistUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockArtistUseCase_Expecter) List(ctx interface{}) *MockArtistUseCase_List_Call {
	return &MockArtistUseCase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockArtistUseCase_List_Call) Run(run func(ctx context.Context)) *MockArtistUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockArtistUseCase_List_Call) Return(_a0 []*entity.Artist, _a1 error) *MockArtistUseCase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistUseCase_List_Call) RunAndReturn(run func(context.Context) ([]*entity.Artist, error)) *MockArtistUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArtistUseCase creates a new instance of MockArtistUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistUseCase {
	mock := &MockArtistUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
