// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublishStatePort is an autogenerated mock type for the EventPublishStatePort type
type MockEventPublishStatePort struct {
	mock.Mock
}

type MockEventPublishStatePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublishStatePort) EXPECT() *MockEventPublishStatePort_Expecter {
	return &MockEventPublishStatePort_Expecter{mock: &_m.Mock}
}

// GetEventOrganizerID provides a mock function with given fields: ctx, eventID
func (_m *MockEventPublishStatePort) GetEventOrganizerID(ctx context.Context, eventID string) (string, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventOrganizerID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventPublishStatePort_GetEventOrganizerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventOrganizerID'
type MockEventPublishStatePort_GetEventOrganizerID_Call struct {
	*mock.Call
}

// GetEventOrganizerID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventPublishStatePort_Expecter) GetEventOrganizerID(ctx interface{}, eventID interface{}) *MockEventPublishStatePort_GetEventOrganizerID_Call {
	return &MockEventPublishStatePort_GetEventOrganizerID_Call{Call: _e.mock.On("GetEventOrganizerID", ctx, eventID)}
}

func (_c *MockEventPublishStatePort_GetEventOrganizerID_Call) Run(run func(ctx context.Context, eventID string)) *MockEventPublishStatePort_GetEventOrganizerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEventPublishStatePort_GetEventOrganizerID_Call) Return(_a0 string, _a1 error) *MockEventPublishStatePort_GetEventOrganizerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventPublishStatePort_GetEventOrganizerID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockEventPublishStatePort_GetEventOrganizerID_Call {
	_c.Call.Return(run)
	return _c
}

// IsEventPublished provides a mock function with given fields: ctx, eventID
func (_m *MockEventPublishStatePort) IsEventPublished(ctx context.Context, eventID string) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsEventPublished")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventPublishStatePort_IsEventPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEventPublished'
type MockEventPublishStatePort_IsEventPublished_Call struct {
	*mock.Call
}

// IsEventPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventPublishStatePort_Expecter) IsEventPublished(ctx interface{}, eventID interface{}) *MockEventPublishStatePort_IsEventPublished_Call {
	return &MockEventPublishStatePort_IsEventPublished_Call{Call: _e.mock.On("IsEventPublished", ctx, eventID)}
}

func (_c *MockEventPublishStatePort_IsEventPublished_Call) Run(run func(ctx context.Context, eventID string)) *MockEventPublishStatePort_IsEventPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEventPublishStatePort_IsEventPublished_Call) Return(_a0 bool, _a1 error) *MockEventPublishStatePort_IsEventPublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventPublishStatePort_IsEventPublished_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockEventPublishStatePort_IsEventPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublishStatePort creates a new instance of MockEventPublishStatePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublishStatePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublishStatePort {
	mock := &MockEventPublishStatePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
