// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishEvent provides a mock function with given fields: ctx, subject, data
func (_m *MockEventPublisher) PublishEvent(ctx context.Context, subject string, data interface{}) error {
	ret := _m.Called(ctx, subject, data)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, subject, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockEventPublisher_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - data interface{}
func (_e *MockEventPublisher_Expecter) PublishEvent(ctx interface{}, subject interface{}, data interface{}) *MockEventPublisher_PublishEvent_Call {
	return &MockEventPublisher_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, subject, data)}
}

func (_c *MockEventPublisher_PublishEvent_Call) Run(run func(ctx context.Context, subject string, data interface{})) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockEventPublisher_PublishEvent_Call) Return(_a0 error) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishEvent_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
