// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockSalesPhaseAnnouncementUseCase is an autogenerated mock type for the SalesPhaseAnnouncementUseCase type
type MockSalesPhaseAnnouncementUseCase struct {
	mock.Mock
}

type MockSalesPhaseAnnouncementUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSalesPhaseAnnouncementUseCase) EXPECT() *MockSalesPhaseAnnouncementUseCase_Expecter {
	return &MockSalesPhaseAnnouncementUseCase_Expecter{mock: &_m.Mock}
}

// AnnounceDiscoveredPhase provides a mock function with given fields: ctx, data
func (_m *MockSalesPhaseAnnouncementUseCase) AnnounceDiscoveredPhase(ctx context.Context, data entity.SalesPhaseDiscoveredData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AnnounceDiscoveredPhase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.SalesPhaseDiscoveredData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceDiscoveredPhase'
type MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call struct {
	*mock.Call
}

// AnnounceDiscoveredPhase is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.SalesPhaseDiscoveredData
func (_e *MockSalesPhaseAnnouncementUseCase_Expecter) AnnounceDiscoveredPhase(ctx interface{}, data interface{}) *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call {
	return &MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call{Call: _e.mock.On("AnnounceDiscoveredPhase", ctx, data)}
}

func (_c *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call) Run(run func(ctx context.Context, data entity.SalesPhaseDiscoveredData)) *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.SalesPhaseDiscoveredData))
	})
	return _c
}

func (_c *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call) Return(_a0 error) *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call) RunAndReturn(run func(context.Context, entity.SalesPhaseDiscoveredData) error) *MockSalesPhaseAnnouncementUseCase_AnnounceDiscoveredPhase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSalesPhaseAnnouncementUseCase creates a new instance of MockSalesPhaseAnnouncementUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSalesPhaseAnnouncementUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSalesPhaseAnnouncementUseCase {
	mock := &MockSalesPhaseAnnouncementUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
