// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArtistImageSyncUseCase is an autogenerated mock type for the ArtistImageSyncUseCase type
type MockArtistImageSyncUseCase struct {
	mock.Mock
}

type MockArtistImageSyncUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistImageSyncUseCase) EXPECT() *MockArtistImageSyncUseCase_Expecter {
	return &MockArtistImageSyncUseCase_Expecter{mock: &_m.Mock}
}

// SyncArtistImage provides a mock function with given fields: ctx, artistID, mbid
func (_m *MockArtistImageSyncUseCase) SyncArtistImage(ctx context.Context, artistID string, mbid string) error {
	ret := _m.Called(ctx, artistID, mbid)

	if len(ret) == 0 {
		panic("no return value specified for SyncArtistImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, artistID, mbid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArtistImageSyncUseCase_SyncArtistImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncArtistImage'
type MockArtistImageSyncUseCase_SyncArtistImage_Call struct {
	*mock.Call
}

// SyncArtistImage is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
//   - mbid string
func (_e *MockArtistImageSyncUseCase_Expecter) SyncArtistImage(ctx interface{}, artistID interface{}, mbid interface{}) *MockArtistImageSyncUseCase_SyncArtistImage_Call {
	return &MockArtistImageSyncUseCase_SyncArtistImage_Call{Call: _e.mock.On("SyncArtistImage", ctx, artistID, mbid)}
}

func (_c *MockArtistImageSyncUseCase_SyncArtistImage_Call) Run(run func(ctx context.Context, artistID string, mbid string)) *MockArtistImageSyncUseCase_SyncArtistImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockArtistImageSyncUseCase_SyncArtistImage_Call) Return(_a0 error) *MockArtistImageSyncUseCase_SyncArtistImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArtistImageSyncUseCase_SyncArtistImage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockArtistImageSyncUseCase_SyncArtistImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArtistImageSyncUseCase creates a new instance of MockArtistImageSyncUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistImageSyncUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistImageSyncUseCase {
	mock := &MockArtistImageSyncUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
