// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockPushNotificationUseCase is an autogenerated mock type for the PushNotificationUseCase type
type MockPushNotificationUseCase struct {
	mock.Mock
}

type MockPushNotificationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushNotificationUseCase) EXPECT() *MockPushNotificationUseCase_Expecter {
	return &MockPushNotificationUseCase_Expecter{mock: &_m.Mock}
}

// NotifyNewConcerts provides a mock function with given fields: ctx, artist, concerts
func (_m *MockPushNotificationUseCase) NotifyNewConcerts(ctx context.Context, artist *entity.Artist, concerts []*entity.Concert) error {
	ret := _m.Called(ctx, artist, concerts)

	if len(ret) == 0 {
		panic("no return value specified for NotifyNewConcerts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist, []*entity.Concert) error); ok {
		r0 = rf(ctx, artist, concerts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushNotificationUseCase_NotifyNewConcerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyNewConcerts'
type MockPushNotificationUseCase_NotifyNewConcerts_Call struct {
	*mock.Call
}

// NotifyNewConcerts is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
//   - concerts []*entity.Concert
func (_e *MockPushNotificationUseCase_Expecter) NotifyNewConcerts(ctx interface{}, artist interface{}, concerts interface{}) *MockPushNotificationUseCase_NotifyNewConcerts_Call {
	return &MockPushNotificationUseCase_NotifyNewConcerts_Call{Call: _e.mock.On("NotifyNewConcerts", ctx, artist, concerts)}
}

func (_c *MockPushNotificationUseCase_NotifyNewConcerts_Call) Run(run func(ctx context.Context, artist *entity.Artist, concerts []*entity.Concert)) *MockPushNotificationUseCase_NotifyNewConcerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Artist), args[2].([]*entity.Concert))
	})
	return _c
}

func (_c *MockPushNotificationUseCase_NotifyNewConcerts_Call) Return(_a0 error) *MockPushNotificationUseCase_NotifyNewConcerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushNotificationUseCase_NotifyNewConcerts_Call) RunAndReturn(run func(context.Context, *entity.Artist, []*entity.Concert) error) *MockPushNotificationUseCase_NotifyNewConcerts_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, userID, endpoint, p256dh, auth
func (_m *MockPushNotificationUseCase) Subscribe(ctx context.Context, userID string, endpoint string, p256dh string, auth string) error {
	ret := _m.Called(ctx, userID, endpoint, p256dh, auth)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, endpoint, p256dh, auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushNotificationUseCase_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPushNotificationUseCase_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - endpoint string
//   - p256dh string
//   - auth string
func (_e *MockPushNotificationUseCase_Expecter) Subscribe(ctx interface{}, userID interface{}, endpoint interface{}, p256dh interface{}, auth interface{}) *MockPushNotificationUseCase_Subscribe_Call {
	return &MockPushNotificationUseCase_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, userID, endpoint, p256dh, auth)}
}

func (_c *MockPushNotificationUseCase_Subscribe_Call) Run(run func(ctx context.Context, userID string, endpoint string, p256dh string, auth string)) *MockPushNotificationUseCase_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockPushNotificationUseCase_Subscribe_Call) Return(_a0 error) *MockPushNotificationUseCase_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushNotificationUseCase_Subscribe_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockPushNotificationUseCase_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: ctx, userID
func (_m *MockPushNotificationUseCase) Unsubscribe(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushNotificationUseCase_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockPushNotificationUseCase_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPushNotificationUseCase_Expecter) Unsubscribe(ctx interface{}, userID interface{}) *MockPushNotificationUseCase_Unsubscribe_Call {
	return &MockPushNotificationUseCase_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, userID)}
}

func (_c *MockPushNotificationUseCase_Unsubscribe_Call) Run(run func(ctx context.Context, userID string)) *MockPushNotificationUseCase_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPushNotificationUseCase_Unsubscribe_Call) Return(_a0 error) *MockPushNotificationUseCase_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushNotificationUseCase_Unsubscribe_Call) RunAndReturn(run func(context.Context, string) error) *MockPushNotificationUseCase_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushNotificationUseCase creates a new instance of MockPushNotificationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushNotificationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushNotificationUseCase {
	mock := &MockPushNotificationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
