// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationUseCase is an autogenerated mock type for the NotificationUseCase type
type MockNotificationUseCase struct {
	mock.Mock
}

type MockNotificationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationUseCase) EXPECT() *MockNotificationUseCase_Expecter {
	return &MockNotificationUseCase_Expecter{mock: &_m.Mock}
}

// MarkDismissed provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationUseCase) MarkDismissed(ctx context.Context, userID string, notificationID string) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkDismissed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationUseCase_MarkDismissed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDismissed'
type MockNotificationUseCase_MarkDismissed_Call struct {
	*mock.Call
}

// MarkDismissed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - notificationID string
func (_e *MockNotificationUseCase_Expecter) MarkDismissed(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationUseCase_MarkDismissed_Call {
	return &MockNotificationUseCase_MarkDismissed_Call{Call: _e.mock.On("MarkDismissed", ctx, userID, notificationID)}
}

func (_c *MockNotificationUseCase_MarkDismissed_Call) Run(run func(ctx context.Context, userID string, notificationID string)) *MockNotificationUseCase_MarkDismissed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotificationUseCase_MarkDismissed_Call) Return(_a0 error) *MockNotificationUseCase_MarkDismissed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUseCase_MarkDismissed_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotificationUseCase_MarkDismissed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationUseCase) MarkRead(ctx context.Context, userID string, notificationID string) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationUseCase_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationUseCase_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - notificationID string
func (_e *MockNotificationUseCase_Expecter) MarkRead(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationUseCase_MarkRead_Call {
	return &MockNotificationUseCase_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, notificationID)}
}

func (_c *MockNotificationUseCase_MarkRead_Call) Run(run func(ctx context.Context, userID string, notificationID string)) *MockNotificationUseCase_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotificationUseCase_MarkRead_Call) Return(_a0 error) *MockNotificationUseCase_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUseCase_MarkRead_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotificationUseCase_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: ctx, userID, typ, payload
func (_m *MockNotificationUseCase) Notify(ctx context.Context, userID string, typ entity.NotificationType, payload *entity.NotificationPayload) (*entity.Notification, error) {
	ret := _m.Called(ctx, userID, typ, payload)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 *entity.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.NotificationType, *entity.NotificationPayload) (*entity.Notification, error)); ok {
		return rf(ctx, userID, typ, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.NotificationType, *entity.NotificationPayload) *entity.Notification); ok {
		r0 = rf(ctx, userID, typ, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.NotificationType, *entity.NotificationPayload) error); ok {
		r1 = rf(ctx, userID, typ, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationUseCase_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotificationUseCase_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - typ entity.NotificationType
//   - payload *entity.NotificationPayload
func (_e *MockNotificationUseCase_Expecter) Notify(ctx interface{}, userID interface{}, typ interface{}, payload interface{}) *MockNotificationUseCase_Notify_Call {
	return &MockNotificationUseCase_Notify_Call{Call: _e.mock.On("Notify", ctx, userID, typ, payload)}
}

func (_c *MockNotificationUseCase_Notify_Call) Run(run func(ctx context.Context, userID string, typ entity.NotificationType, payload *entity.NotificationPayload)) *MockNotificationUseCase_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.NotificationType), args[3].(*entity.NotificationPayload))
	})
	return _c
}

func (_c *MockNotificationUseCase_Notify_Call) Return(_a0 *entity.Notification, _a1 error) *MockNotificationUseCase_Notify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationUseCase_Notify_Call) RunAndReturn(run func(context.Context, string, entity.NotificationType, *entity.NotificationPayload) (*entity.Notification, error)) *MockNotificationUseCase_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationUseCase creates a new instance of MockNotificationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationUseCase {
	mock := &MockNotificationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
