// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// MockImageStorer is an autogenerated mock type for the ImageStorer type
type MockImageStorer struct {
	mock.Mock
}

type MockImageStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageStorer) EXPECT() *MockImageStorer_Expecter {
	return &MockImageStorer_Expecter{mock: &_m.Mock}
}

// SignedPutURLForOriginal provides a mock function with given fields: ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl
func (_m *MockImageStorer) SignedPutURLForOriginal(ctx context.Context, bucket string, organizerID string, mediaID string, contentType string, maxBytes int64, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SignedPutURLForOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int64, time.Duration) (string, error)); ok {
		return rf(ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int64, time.Duration) string); ok {
		r0 = rf(ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int64, time.Duration) error); ok {
		r1 = rf(ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageStorer_SignedPutURLForOriginal_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_SignedPutURLForOriginal_Call struct {
	*mock.Call
}

// SignedPutURLForOriginal is a helper method to define mock.On call
func (_e *MockImageStorer_Expecter) SignedPutURLForOriginal(ctx interface{}, bucket interface{}, organizerID interface{}, mediaID interface{}, contentType interface{}, maxBytes interface{}, ttl interface{}) *MockImageStorer_SignedPutURLForOriginal_Call {
	return &MockImageStorer_SignedPutURLForOriginal_Call{Call: _e.mock.On("SignedPutURLForOriginal", ctx, bucket, organizerID, mediaID, contentType, maxBytes, ttl)}
}

func (_c *MockImageStorer_SignedPutURLForOriginal_Call) Run(run func(ctx context.Context, bucket string, organizerID string, mediaID string, contentType string, maxBytes int64, ttl time.Duration)) *MockImageStorer_SignedPutURLForOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int64), args[6].(time.Duration))
	})
	return _c
}

func (_c *MockImageStorer_SignedPutURLForOriginal_Call) Return(_a0 string, _a1 error) *MockImageStorer_SignedPutURLForOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageStorer_SignedPutURLForOriginal_Call) RunAndReturn(run func(context.Context, string, string, string, string, int64, time.Duration) (string, error)) *MockImageStorer_SignedPutURLForOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOriginal provides a mock function with given fields: ctx, bucket, organizerID, mediaID
func (_m *MockImageStorer) ReadOriginal(ctx context.Context, bucket string, organizerID string, mediaID string) ([]byte, error) {
	ret := _m.Called(ctx, bucket, organizerID, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for ReadOriginal")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, error)); ok {
		return rf(ctx, bucket, organizerID, mediaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = rf(ctx, bucket, organizerID, mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, bucket, organizerID, mediaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageStorer_ReadOriginal_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_ReadOriginal_Call struct {
	*mock.Call
}

// ReadOriginal is a helper method to define mock.On call
func (_e *MockImageStorer_Expecter) ReadOriginal(ctx interface{}, bucket interface{}, organizerID interface{}, mediaID interface{}) *MockImageStorer_ReadOriginal_Call {
	return &MockImageStorer_ReadOriginal_Call{Call: _e.mock.On("ReadOriginal", ctx, bucket, organizerID, mediaID)}
}

func (_c *MockImageStorer_ReadOriginal_Call) Run(run func(ctx context.Context, bucket string, organizerID string, mediaID string)) *MockImageStorer_ReadOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockImageStorer_ReadOriginal_Call) Return(_a0 []byte, _a1 error) *MockImageStorer_ReadOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageStorer_ReadOriginal_Call) RunAndReturn(run func(context.Context, string, string, string) ([]byte, error)) *MockImageStorer_ReadOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOriginal provides a mock function with given fields: ctx, bucket, organizerID, mediaID
func (_m *MockImageStorer) DeleteOriginal(ctx context.Context, bucket string, organizerID string, mediaID string) error {
	ret := _m.Called(ctx, bucket, organizerID, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOriginal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bucket, organizerID, mediaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorer_DeleteOriginal_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_DeleteOriginal_Call struct {
	*mock.Call
}

// DeleteOriginal is a helper method to define mock.On call
func (_e *MockImageStorer_Expecter) DeleteOriginal(ctx interface{}, bucket interface{}, organizerID interface{}, mediaID interface{}) *MockImageStorer_DeleteOriginal_Call {
	return &MockImageStorer_DeleteOriginal_Call{Call: _e.mock.On("DeleteOriginal", ctx, bucket, organizerID, mediaID)}
}

func (_c *MockImageStorer_DeleteOriginal_Call) Run(run func(ctx context.Context, bucket string, organizerID string, mediaID string)) *MockImageStorer_DeleteOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockImageStorer_DeleteOriginal_Call) Return(_a0 error) *MockImageStorer_DeleteOriginal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStorer_DeleteOriginal_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockImageStorer_DeleteOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// PutVariant provides a mock function with given fields: ctx, bucket, organizerID, mediaID, variant, contentType, data
func (_m *MockImageStorer) PutVariant(ctx context.Context, bucket string, organizerID string, mediaID string, variant string, contentType string, data []byte) error {
	ret := _m.Called(ctx, bucket, organizerID, mediaID, variant, contentType, data)

	if len(ret) == 0 {
		panic("no return value specified for PutVariant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, []byte) error); ok {
		r0 = rf(ctx, bucket, organizerID, mediaID, variant, contentType, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorer_PutVariant_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_PutVariant_Call struct {
	*mock.Call
}

// PutVariant is a helper method to define mock.On call
func (_e *MockImageStorer_Expecter) PutVariant(ctx interface{}, bucket interface{}, organizerID interface{}, mediaID interface{}, variant interface{}, contentType interface{}, data interface{}) *MockImageStorer_PutVariant_Call {
	return &MockImageStorer_PutVariant_Call{Call: _e.mock.On("PutVariant", ctx, bucket, organizerID, mediaID, variant, contentType, data)}
}

func (_c *MockImageStorer_PutVariant_Call) Run(run func(ctx context.Context, bucket string, organizerID string, mediaID string, variant string, contentType string, data []byte)) *MockImageStorer_PutVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].([]byte))
	})
	return _c
}

func (_c *MockImageStorer_PutVariant_Call) Return(_a0 error) *MockImageStorer_PutVariant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStorer_PutVariant_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, []byte) error) *MockImageStorer_PutVariant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVariants provides a mock function with given fields: ctx, bucket, organizerID, mediaID
func (_m *MockImageStorer) DeleteVariants(ctx context.Context, bucket string, organizerID string, mediaID string) error {
	ret := _m.Called(ctx, bucket, organizerID, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVariants")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bucket, organizerID, mediaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorer_DeleteVariants_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_DeleteVariants_Call struct {
	*mock.Call
}

// DeleteVariants is a helper method to define mock.On call
func (_e *MockImageStorer_Expecter) DeleteVariants(ctx interface{}, bucket interface{}, organizerID interface{}, mediaID interface{}) *MockImageStorer_DeleteVariants_Call {
	return &MockImageStorer_DeleteVariants_Call{Call: _e.mock.On("DeleteVariants", ctx, bucket, organizerID, mediaID)}
}

func (_c *MockImageStorer_DeleteVariants_Call) Run(run func(ctx context.Context, bucket string, organizerID string, mediaID string)) *MockImageStorer_DeleteVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockImageStorer_DeleteVariants_Call) Return(_a0 error) *MockImageStorer_DeleteVariants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStorer_DeleteVariants_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockImageStorer_DeleteVariants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageStorer creates a new instance of MockImageStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageStorer {
	mock := &MockImageStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
