// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConcertUseCase creates a new instance of MockConcertUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcertUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcertUseCase {
	mock := &MockConcertUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConcertUseCase is an autogenerated mock type for the ConcertUseCase type
type MockConcertUseCase struct {
	mock.Mock
}

type MockConcertUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcertUseCase) EXPECT() *MockConcertUseCase_Expecter {
	return &MockConcertUseCase_Expecter{mock: &_m.Mock}
}

// ListByArtist provides a mock function for the type MockConcertUseCase
func (_mock *MockConcertUseCase) ListByArtist(ctx context.Context, artistID string) ([]*entity.Concert, error) {
	ret := _mock.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for ListByArtist")
	}

	var r0 []*entity.Concert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Concert, error)); ok {
		return returnFunc(ctx, artistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Concert); ok {
		r0 = returnFunc(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConcertUseCase_ListByArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByArtist'
type MockConcertUseCase_ListByArtist_Call struct {
	*mock.Call
}

// ListByArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockConcertUseCase_Expecter) ListByArtist(ctx interface{}, artistID interface{}) *MockConcertUseCase_ListByArtist_Call {
	return &MockConcertUseCase_ListByArtist_Call{Call: _e.mock.On("ListByArtist", ctx, artistID)}
}

func (_c *MockConcertUseCase_ListByArtist_Call) Run(run func(ctx context.Context, artistID string)) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConcertUseCase_ListByArtist_Call) Return(concerts []*entity.Concert, err error) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Return(concerts, err)
	return _c
}

func (_c *MockConcertUseCase_ListByArtist_Call) RunAndReturn(run func(ctx context.Context, artistID string) ([]*entity.Concert, error)) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Return(run)
	return _c
}

// SearchNewConcerts provides a mock function for the type MockConcertUseCase
func (_mock *MockConcertUseCase) SearchNewConcerts(ctx context.Context, artistID string) ([]*entity.Concert, error) {
	ret := _mock.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for SearchNewConcerts")
	}

	var r0 []*entity.Concert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Concert, error)); ok {
		return returnFunc(ctx, artistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Concert); ok {
		r0 = returnFunc(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConcertUseCase_SearchNewConcerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchNewConcerts'
type MockConcertUseCase_SearchNewConcerts_Call struct {
	*mock.Call
}

// SearchNewConcerts is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockConcertUseCase_Expecter) SearchNewConcerts(ctx interface{}, artistID interface{}) *MockConcertUseCase_SearchNewConcerts_Call {
	return &MockConcertUseCase_SearchNewConcerts_Call{Call: _e.mock.On("SearchNewConcerts", ctx, artistID)}
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) Run(run func(ctx context.Context, artistID string)) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) Return(concerts []*entity.Concert, err error) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Return(concerts, err)
	return _c
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) RunAndReturn(run func(ctx context.Context, artistID string) ([]*entity.Concert, error)) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Return(run)
	return _c
}
