// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	usecase "github.com/liverty-music/backend/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockPocketSignVerifier is an autogenerated mock type for the PocketSignVerifier type
type MockPocketSignVerifier struct {
	mock.Mock
}

type MockPocketSignVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPocketSignVerifier) EXPECT() *MockPocketSignVerifier_Expecter {
	return &MockPocketSignVerifier_Expecter{mock: &_m.Mock}
}

// IssueChallenge provides a mock function with given fields: ctx, method
func (_m *MockPocketSignVerifier) IssueChallenge(ctx context.Context, method entity.VerificationMethod) (*usecase.PocketSignChallenge, error) {
	ret := _m.Called(ctx, method)

	if len(ret) == 0 {
		panic("no return value specified for IssueChallenge")
	}

	var r0 *usecase.PocketSignChallenge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.VerificationMethod) (*usecase.PocketSignChallenge, error)); ok {
		return rf(ctx, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.VerificationMethod) *usecase.PocketSignChallenge); ok {
		r0 = rf(ctx, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.PocketSignChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.VerificationMethod) error); ok {
		r1 = rf(ctx, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPocketSignVerifier_IssueChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueChallenge'
type MockPocketSignVerifier_IssueChallenge_Call struct {
	*mock.Call
}

// IssueChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - method entity.VerificationMethod
func (_e *MockPocketSignVerifier_Expecter) IssueChallenge(ctx interface{}, method interface{}) *MockPocketSignVerifier_IssueChallenge_Call {
	return &MockPocketSignVerifier_IssueChallenge_Call{Call: _e.mock.On("IssueChallenge", ctx, method)}
}

func (_c *MockPocketSignVerifier_IssueChallenge_Call) Run(run func(ctx context.Context, method entity.VerificationMethod)) *MockPocketSignVerifier_IssueChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.VerificationMethod))
	})
	return _c
}

func (_c *MockPocketSignVerifier_IssueChallenge_Call) Return(_a0 *usecase.PocketSignChallenge, _a1 error) *MockPocketSignVerifier_IssueChallenge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPocketSignVerifier_IssueChallenge_Call) RunAndReturn(run func(context.Context, entity.VerificationMethod) (*usecase.PocketSignChallenge, error)) *MockPocketSignVerifier_IssueChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateResponse provides a mock function with given fields: ctx, sessionID, signedResponse
func (_m *MockPocketSignVerifier) ValidateResponse(ctx context.Context, sessionID string, signedResponse []byte) (*usecase.PocketSignResult, error) {
	ret := _m.Called(ctx, sessionID, signedResponse)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResponse")
	}

	var r0 *usecase.PocketSignResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (*usecase.PocketSignResult, error)); ok {
		return rf(ctx, sessionID, signedResponse)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *usecase.PocketSignResult); ok {
		r0 = rf(ctx, sessionID, signedResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.PocketSignResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, sessionID, signedResponse)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPocketSignVerifier_ValidateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateResponse'
type MockPocketSignVerifier_ValidateResponse_Call struct {
	*mock.Call
}

// ValidateResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - signedResponse []byte
func (_e *MockPocketSignVerifier_Expecter) ValidateResponse(ctx interface{}, sessionID interface{}, signedResponse interface{}) *MockPocketSignVerifier_ValidateResponse_Call {
	return &MockPocketSignVerifier_ValidateResponse_Call{Call: _e.mock.On("ValidateResponse", ctx, sessionID, signedResponse)}
}

func (_c *MockPocketSignVerifier_ValidateResponse_Call) Run(run func(ctx context.Context, sessionID string, signedResponse []byte)) *MockPocketSignVerifier_ValidateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockPocketSignVerifier_ValidateResponse_Call) Return(_a0 *usecase.PocketSignResult, _a1 error) *MockPocketSignVerifier_ValidateResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPocketSignVerifier_ValidateResponse_Call) RunAndReturn(run func(context.Context, string, []byte) (*usecase.PocketSignResult, error)) *MockPocketSignVerifier_ValidateResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Recheck provides a mock function with given fields: ctx, pocketSignUserID
func (_m *MockPocketSignVerifier) Recheck(ctx context.Context, pocketSignUserID string) (*usecase.PocketSignRecheckResult, error) {
	ret := _m.Called(ctx, pocketSignUserID)

	if len(ret) == 0 {
		panic("no return value specified for Recheck")
	}

	var r0 *usecase.PocketSignRecheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usecase.PocketSignRecheckResult, error)); ok {
		return rf(ctx, pocketSignUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usecase.PocketSignRecheckResult); ok {
		r0 = rf(ctx, pocketSignUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.PocketSignRecheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pocketSignUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPocketSignVerifier_Recheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recheck'
type MockPocketSignVerifier_Recheck_Call struct {
	*mock.Call
}

// Recheck is a helper method to define mock.On call
//   - ctx context.Context
//   - pocketSignUserID string
func (_e *MockPocketSignVerifier_Expecter) Recheck(ctx interface{}, pocketSignUserID interface{}) *MockPocketSignVerifier_Recheck_Call {
	return &MockPocketSignVerifier_Recheck_Call{Call: _e.mock.On("Recheck", ctx, pocketSignUserID)}
}

func (_c *MockPocketSignVerifier_Recheck_Call) Run(run func(ctx context.Context, pocketSignUserID string)) *MockPocketSignVerifier_Recheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPocketSignVerifier_Recheck_Call) Return(_a0 *usecase.PocketSignRecheckResult, _a1 error) *MockPocketSignVerifier_Recheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPocketSignVerifier_Recheck_Call) RunAndReturn(run func(context.Context, string) (*usecase.PocketSignRecheckResult, error)) *MockPocketSignVerifier_Recheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPocketSignVerifier creates a new instance of MockPocketSignVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPocketSignVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPocketSignVerifier {
	mock := &MockPocketSignVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
