// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTicketJourneyUseCase is an autogenerated mock type for the TicketJourneyUseCase type
type MockTicketJourneyUseCase struct {
	mock.Mock
}

type MockTicketJourneyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketJourneyUseCase) EXPECT() *MockTicketJourneyUseCase_Expecter {
	return &MockTicketJourneyUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID, eventID
func (_m *MockTicketJourneyUseCase) Delete(ctx context.Context, userID string, eventID string) error {
	ret := _m.Called(ctx, userID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketJourneyUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTicketJourneyUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventID string
func (_e *MockTicketJourneyUseCase_Expecter) Delete(ctx interface{}, userID interface{}, eventID interface{}) *MockTicketJourneyUseCase_Delete_Call {
	return &MockTicketJourneyUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, eventID)}
}

func (_c *MockTicketJourneyUseCase_Delete_Call) Run(run func(ctx context.Context, userID string, eventID string)) *MockTicketJourneyUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTicketJourneyUseCase_Delete_Call) Return(_a0 error) *MockTicketJourneyUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketJourneyUseCase_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTicketJourneyUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockTicketJourneyUseCase) ListByUser(ctx context.Context, userID string) ([]*entity.TicketJourney, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entity.TicketJourney
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.TicketJourney, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.TicketJourney); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TicketJourney)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketJourneyUseCase_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTicketJourneyUseCase_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTicketJourneyUseCase_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockTicketJourneyUseCase_ListByUser_Call {
	return &MockTicketJourneyUseCase_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTicketJourneyUseCase_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTicketJourneyUseCase_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTicketJourneyUseCase_ListByUser_Call) Return(_a0 []*entity.TicketJourney, _a1 error) *MockTicketJourneyUseCase_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketJourneyUseCase_ListByUser_Call) RunAndReturn(run func(context.Context, string) ([]*entity.TicketJourney, error)) *MockTicketJourneyUseCase_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, userID, eventID, status
func (_m *MockTicketJourneyUseCase) SetStatus(ctx context.Context, userID string, eventID string, status entity.TicketJourneyStatus) error {
	ret := _m.Called(ctx, userID, eventID, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entity.TicketJourneyStatus) error); ok {
		r0 = rf(ctx, userID, eventID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketJourneyUseCase_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockTicketJourneyUseCase_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventID string
//   - status entity.TicketJourneyStatus
func (_e *MockTicketJourneyUseCase_Expecter) SetStatus(ctx interface{}, userID interface{}, eventID interface{}, status interface{}) *MockTicketJourneyUseCase_SetStatus_Call {
	return &MockTicketJourneyUseCase_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, userID, eventID, status)}
}

func (_c *MockTicketJourneyUseCase_SetStatus_Call) Run(run func(ctx context.Context, userID string, eventID string, status entity.TicketJourneyStatus)) *MockTicketJourneyUseCase_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(entity.TicketJourneyStatus))
	})
	return _c
}

func (_c *MockTicketJourneyUseCase_SetStatus_Call) Return(_a0 error) *MockTicketJourneyUseCase_SetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketJourneyUseCase_SetStatus_Call) RunAndReturn(run func(context.Context, string, string, entity.TicketJourneyStatus) error) *MockTicketJourneyUseCase_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketJourneyUseCase creates a new instance of MockTicketJourneyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketJourneyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketJourneyUseCase {
	mock := &MockTicketJourneyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
