// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	usecase "github.com/liverty-music/backend/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockIdentityVerificationUseCase is an autogenerated mock type for the IdentityVerificationUseCase type
type MockIdentityVerificationUseCase struct {
	mock.Mock
}

type MockIdentityVerificationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityVerificationUseCase) EXPECT() *MockIdentityVerificationUseCase_Expecter {
	return &MockIdentityVerificationUseCase_Expecter{mock: &_m.Mock}
}

// StartVerify provides a mock function with given fields: ctx, userID, method
func (_m *MockIdentityVerificationUseCase) StartVerify(ctx context.Context, userID string, method entity.VerificationMethod) (*usecase.PocketSignChallenge, error) {
	ret := _m.Called(ctx, userID, method)

	if len(ret) == 0 {
		panic("no return value specified for StartVerify")
	}

	var r0 *usecase.PocketSignChallenge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.VerificationMethod) (*usecase.PocketSignChallenge, error)); ok {
		return rf(ctx, userID, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.VerificationMethod) *usecase.PocketSignChallenge); ok {
		r0 = rf(ctx, userID, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.PocketSignChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.VerificationMethod) error); ok {
		r1 = rf(ctx, userID, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityVerificationUseCase_StartVerify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartVerify'
type MockIdentityVerificationUseCase_StartVerify_Call struct {
	*mock.Call
}

// StartVerify is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - method entity.VerificationMethod
func (_e *MockIdentityVerificationUseCase_Expecter) StartVerify(ctx interface{}, userID interface{}, method interface{}) *MockIdentityVerificationUseCase_StartVerify_Call {
	return &MockIdentityVerificationUseCase_StartVerify_Call{Call: _e.mock.On("StartVerify", ctx, userID, method)}
}

func (_c *MockIdentityVerificationUseCase_StartVerify_Call) Run(run func(ctx context.Context, userID string, method entity.VerificationMethod)) *MockIdentityVerificationUseCase_StartVerify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.VerificationMethod))
	})
	return _c
}

func (_c *MockIdentityVerificationUseCase_StartVerify_Call) Return(_a0 *usecase.PocketSignChallenge, _a1 error) *MockIdentityVerificationUseCase_StartVerify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityVerificationUseCase_StartVerify_Call) RunAndReturn(run func(context.Context, string, entity.VerificationMethod) (*usecase.PocketSignChallenge, error)) *MockIdentityVerificationUseCase_StartVerify_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteVerify provides a mock function with given fields: ctx, userID, sessionID, signedResponse
func (_m *MockIdentityVerificationUseCase) CompleteVerify(ctx context.Context, userID string, sessionID string, signedResponse []byte) (*entity.VerifiedIdentity, error) {
	ret := _m.Called(ctx, userID, sessionID, signedResponse)

	if len(ret) == 0 {
		panic("no return value specified for CompleteVerify")
	}

	var r0 *entity.VerifiedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (*entity.VerifiedIdentity, error)); ok {
		return rf(ctx, userID, sessionID, signedResponse)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) *entity.VerifiedIdentity); ok {
		r0 = rf(ctx, userID, sessionID, signedResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.VerifiedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, userID, sessionID, signedResponse)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityVerificationUseCase_CompleteVerify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteVerify'
type MockIdentityVerificationUseCase_CompleteVerify_Call struct {
	*mock.Call
}

// CompleteVerify is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
//   - signedResponse []byte
func (_e *MockIdentityVerificationUseCase_Expecter) CompleteVerify(ctx interface{}, userID interface{}, sessionID interface{}, signedResponse interface{}) *MockIdentityVerificationUseCase_CompleteVerify_Call {
	return &MockIdentityVerificationUseCase_CompleteVerify_Call{Call: _e.mock.On("CompleteVerify", ctx, userID, sessionID, signedResponse)}
}

func (_c *MockIdentityVerificationUseCase_CompleteVerify_Call) Run(run func(ctx context.Context, userID string, sessionID string, signedResponse []byte)) *MockIdentityVerificationUseCase_CompleteVerify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockIdentityVerificationUseCase_CompleteVerify_Call) Return(_a0 *entity.VerifiedIdentity, _a1 error) *MockIdentityVerificationUseCase_CompleteVerify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityVerificationUseCase_CompleteVerify_Call) RunAndReturn(run func(context.Context, string, string, []byte) (*entity.VerifiedIdentity, error)) *MockIdentityVerificationUseCase_CompleteVerify_Call {
	_c.Call.Return(run)
	return _c
}

// ReCheck provides a mock function with given fields: ctx, userID
func (_m *MockIdentityVerificationUseCase) ReCheck(ctx context.Context, userID string) (*entity.VerifiedIdentity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReCheck")
	}

	var r0 *entity.VerifiedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.VerifiedIdentity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.VerifiedIdentity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.VerifiedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityVerificationUseCase_ReCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReCheck'
type MockIdentityVerificationUseCase_ReCheck_Call struct {
	*mock.Call
}

// ReCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIdentityVerificationUseCase_Expecter) ReCheck(ctx interface{}, userID interface{}) *MockIdentityVerificationUseCase_ReCheck_Call {
	return &MockIdentityVerificationUseCase_ReCheck_Call{Call: _e.mock.On("ReCheck", ctx, userID)}
}

func (_c *MockIdentityVerificationUseCase_ReCheck_Call) Run(run func(ctx context.Context, userID string)) *MockIdentityVerificationUseCase_ReCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityVerificationUseCase_ReCheck_Call) Return(_a0 *entity.VerifiedIdentity, _a1 error) *MockIdentityVerificationUseCase_ReCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityVerificationUseCase_ReCheck_Call) RunAndReturn(run func(context.Context, string) (*entity.VerifiedIdentity, error)) *MockIdentityVerificationUseCase_ReCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyVerificationStatus provides a mock function with given fields: ctx, userID
func (_m *MockIdentityVerificationUseCase) GetMyVerificationStatus(ctx context.Context, userID string) (entity.VerificationLevel, *entity.VerifiedIdentity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyVerificationStatus")
	}

	var r0 entity.VerificationLevel
	var r1 *entity.VerifiedIdentity
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.VerificationLevel, *entity.VerifiedIdentity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.VerificationLevel); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entity.VerificationLevel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *entity.VerifiedIdentity); ok {
		r1 = rf(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.VerifiedIdentity)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIdentityVerificationUseCase_GetMyVerificationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyVerificationStatus'
type MockIdentityVerificationUseCase_GetMyVerificationStatus_Call struct {
	*mock.Call
}

// GetMyVerificationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIdentityVerificationUseCase_Expecter) GetMyVerificationStatus(ctx interface{}, userID interface{}) *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call {
	return &MockIdentityVerificationUseCase_GetMyVerificationStatus_Call{Call: _e.mock.On("GetMyVerificationStatus", ctx, userID)}
}

func (_c *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call) Run(run func(ctx context.Context, userID string)) *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call) Return(_a0 entity.VerificationLevel, _a1 *entity.VerifiedIdentity, _a2 error) *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call) RunAndReturn(run func(context.Context, string) (entity.VerificationLevel, *entity.VerifiedIdentity, error)) *MockIdentityVerificationUseCase_GetMyVerificationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *MockIdentityVerificationUseCase) Delete(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdentityVerificationUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIdentityVerificationUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIdentityVerificationUseCase_Expecter) Delete(ctx interface{}, userID interface{}) *MockIdentityVerificationUseCase_Delete_Call {
	return &MockIdentityVerificationUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockIdentityVerificationUseCase_Delete_Call) Run(run func(ctx context.Context, userID string)) *MockIdentityVerificationUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityVerificationUseCase_Delete_Call) Return(_a0 error) *MockIdentityVerificationUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdentityVerificationUseCase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockIdentityVerificationUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityVerificationUseCase creates a new instance of MockIdentityVerificationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityVerificationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityVerificationUseCase {
	mock := &MockIdentityVerificationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
