// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockConcertCreationUseCase is an autogenerated mock type for the ConcertCreationUseCase type
type MockConcertCreationUseCase struct {
	mock.Mock
}

type MockConcertCreationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcertCreationUseCase) EXPECT() *MockConcertCreationUseCase_Expecter {
	return &MockConcertCreationUseCase_Expecter{mock: &_m.Mock}
}

// CreateFromDiscovered provides a mock function with given fields: ctx, data
func (_m *MockConcertCreationUseCase) CreateFromDiscovered(ctx context.Context, data entity.ConcertDiscoveredData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromDiscovered")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ConcertDiscoveredData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConcertCreationUseCase_CreateFromDiscovered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromDiscovered'
type MockConcertCreationUseCase_CreateFromDiscovered_Call struct {
	*mock.Call
}

// CreateFromDiscovered is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.ConcertDiscoveredData
func (_e *MockConcertCreationUseCase_Expecter) CreateFromDiscovered(ctx interface{}, data interface{}) *MockConcertCreationUseCase_CreateFromDiscovered_Call {
	return &MockConcertCreationUseCase_CreateFromDiscovered_Call{Call: _e.mock.On("CreateFromDiscovered", ctx, data)}
}

func (_c *MockConcertCreationUseCase_CreateFromDiscovered_Call) Run(run func(ctx context.Context, data entity.ConcertDiscoveredData)) *MockConcertCreationUseCase_CreateFromDiscovered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ConcertDiscoveredData))
	})
	return _c
}

func (_c *MockConcertCreationUseCase_CreateFromDiscovered_Call) Return(_a0 error) *MockConcertCreationUseCase_CreateFromDiscovered_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConcertCreationUseCase_CreateFromDiscovered_Call) RunAndReturn(run func(context.Context, entity.ConcertDiscoveredData) error) *MockConcertCreationUseCase_CreateFromDiscovered_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConcertCreationUseCase creates a new instance of MockConcertCreationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcertCreationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcertCreationUseCase {
	mock := &MockConcertCreationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
