// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockArtistUseCase is an autogenerated mock type for the ArtistUseCase type
type MockArtistUseCase struct {
	mock.Mock
}

type MockArtistUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistUseCase) EXPECT() *MockArtistUseCase_Expecter {
	return &MockArtistUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, artist
func (_m *MockArtistUseCase) Create(ctx context.Context, artist *entity.Artist) (*entity.Artist, error) {
	ret := _m.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist) (*entity.Artist, error)); ok {
		return rf(ctx, artist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Artist) *entity.Artist); ok {
		r0 = rf(ctx, artist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Artist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Artist) error); ok {
		r1 = rf(ctx, artist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArtistUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.Artist
func (_e *MockArtistUseCase_Expecter) Create(ctx interface{}, artist interface{}) *MockArtistUseCase_Create_Call {
	return &MockArtistUseCase_Create_Call{Call: _e.mock.On("Create", ctx, artist)}
}

func (_c *MockArtistUseCase_Create_Call) Run(run func(ctx context.Context, artist *entity.Artist)) *MockArtistUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Artist))
	})
	return _c
}

func (_c *MockArtistUseCase_Create_Call) Return(_a0 *entity.Artist, _a1 error) *MockArtistUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistUseCase_Create_Call) RunAndReturn(run func(context.Context, *entity.Artist) (*entity.Artist, error)) *MockArtistUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOfficialSite provides a mock function with given fields: ctx, site
func (_m *MockArtistUseCase) CreateOfficialSite(ctx context.Context, site *entity.OfficialSite) error {
	ret := _m.Called(ctx, site)

	if len(ret) == 0 {
		panic("no return value specified for CreateOfficialSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OfficialSite) error); ok {
		r0 = rf(ctx, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArtistUseCase_CreateOfficialSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOfficialSite'
type MockArtistUseCase_CreateOfficialSite_Call struct {
	*mock.Call
}

// CreateOfficialSite is a helper method to define mock.On call
//   - ctx context.Context
//   - site *entity.OfficialSite
func (_e *MockArtistUseCase_Expecter) CreateOfficialSite(ctx interface{}, site interface{}) *MockArtistUseCase_CreateOfficialSite_Call {
	return &MockArtistUseCase_CreateOfficialSite_Call{Call: _e.mock.On("CreateOfficialSite", ctx, site)}
}

func (_c *MockArtistUseCase_CreateOfficialSite_Call) Run(run func(ctx context.Context, site *entity.OfficialSite)) *MockArtistUseCase_CreateOfficialSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OfficialSite))
	})
	return _c
}

func (_c *MockArtistUseCase_CreateOfficialSite_Call) Return(_a0 error) *MockArtistUseCase_CreateOfficialSite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArtistUseCase_CreateOfficialSite_Call) RunAndReturn(run func(context.Context, *entity.OfficialSite) error) *MockArtistUseCase_CreateOfficialSite_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfficialSite provides a mock function with given fields: ctx, artistID
func (_m *MockArtistUseCase) GetOfficialSite(ctx context.Context, artistID string) (*entity.OfficialSite, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficialSite")
	}

	var r0 *entity.OfficialSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.OfficialSite, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.OfficialSite); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OfficialSite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistUseCase_GetOfficialSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfficialSite'
type MockArtistUseCase_GetOfficialSite_Call struct {
	*mock.Call
}

// GetOfficialSite is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockArtistUseCase_Expecter) GetOfficialSite(ctx interface{}, artistID interface{}) *MockArtistUseCase_GetOfficialSite_Call {
	return &MockArtistUseCase_GetOfficialSite_Call{Call: _e.mock.On("GetOfficialSite", ctx, artistID)}
}

func (_c *MockArtistUseCase_GetOfficialSite_Call) Run(run func(ctx context.Context, artistID string)) *MockArtistUseCase_GetOfficialSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArtistUseCase_GetOfficialSite_Call) Return(_a0 *entity.OfficialSite, _a1 error) *MockArtistUseCase_GetOfficialSite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistUseCase_GetOfficialSite_Call) RunAndReturn(run func(context.Context, string) (*entity.OfficialSite, error)) *MockArtistUseCase_GetOfficialSite_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockArtistUseCase) List(ctx context.Context) ([]*entity.Artist, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Artist, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Artist); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Artist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArtistUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockArtistUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockArtistUseCase_Expecter) List(ctx interface{}) *MockArtistUseCase_List_Call {
	return &MockArtistUseCase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockArtistUseCase_List_Call) Run(run func(ctx context.Context)) *MockArtistUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockArtistUseCase_List_Call) Return(_a0 []*entity.Artist, _a1 error) *MockArtistUseCase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArtistUseCase_List_Call) RunAndReturn(run func(context.Context) ([]*entity.Artist, error)) *MockArtistUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArtistUseCase creates a new instance of MockArtistUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistUseCase {
	mock := &MockArtistUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
