// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/liverty-music/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockConcertUseCase is an autogenerated mock type for the ConcertUseCase type
type MockConcertUseCase struct {
	mock.Mock
}

type MockConcertUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcertUseCase) EXPECT() *MockConcertUseCase_Expecter {
	return &MockConcertUseCase_Expecter{mock: &_m.Mock}
}

// ListByArtist provides a mock function with given fields: ctx, artistID
func (_m *MockConcertUseCase) ListByArtist(ctx context.Context, artistID string) ([]*entity.Concert, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for ListByArtist")
	}

	var r0 []*entity.Concert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Concert, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Concert); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_ListByArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByArtist'
type MockConcertUseCase_ListByArtist_Call struct {
	*mock.Call
}

// ListByArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockConcertUseCase_Expecter) ListByArtist(ctx interface{}, artistID interface{}) *MockConcertUseCase_ListByArtist_Call {
	return &MockConcertUseCase_ListByArtist_Call{Call: _e.mock.On("ListByArtist", ctx, artistID)}
}

func (_c *MockConcertUseCase_ListByArtist_Call) Run(run func(ctx context.Context, artistID string)) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConcertUseCase_ListByArtist_Call) Return(_a0 []*entity.Concert, _a1 error) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_ListByArtist_Call) RunAndReturn(run func(context.Context, string) ([]*entity.Concert, error)) *MockConcertUseCase_ListByArtist_Call {
	_c.Call.Return(run)
	return _c
}

// ListByArtists provides a mock function with given fields: ctx, artistIDs, home
func (_m *MockConcertUseCase) ListByArtists(ctx context.Context, artistIDs []string, home *entity.Home) ([]*entity.ProximityGroup, error) {
	ret := _m.Called(ctx, artistIDs, home)

	if len(ret) == 0 {
		panic("no return value specified for ListByArtists")
	}

	var r0 []*entity.ProximityGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, *entity.Home) ([]*entity.ProximityGroup, error)); ok {
		return rf(ctx, artistIDs, home)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, *entity.Home) []*entity.ProximityGroup); ok {
		r0 = rf(ctx, artistIDs, home)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProximityGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, *entity.Home) error); ok {
		r1 = rf(ctx, artistIDs, home)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_ListByArtists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByArtists'
type MockConcertUseCase_ListByArtists_Call struct {
	*mock.Call
}

// ListByArtists is a helper method to define mock.On call
//   - ctx context.Context
//   - artistIDs []string
//   - home *entity.Home
func (_e *MockConcertUseCase_Expecter) ListByArtists(ctx interface{}, artistIDs interface{}, home interface{}) *MockConcertUseCase_ListByArtists_Call {
	return &MockConcertUseCase_ListByArtists_Call{Call: _e.mock.On("ListByArtists", ctx, artistIDs, home)}
}

func (_c *MockConcertUseCase_ListByArtists_Call) Run(run func(ctx context.Context, artistIDs []string, home *entity.Home)) *MockConcertUseCase_ListByArtists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(*entity.Home))
	})
	return _c
}

func (_c *MockConcertUseCase_ListByArtists_Call) Return(_a0 []*entity.ProximityGroup, _a1 error) *MockConcertUseCase_ListByArtists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_ListByArtists_Call) RunAndReturn(run func(context.Context, []string, *entity.Home) ([]*entity.ProximityGroup, error)) *MockConcertUseCase_ListByArtists_Call {
	_c.Call.Return(run)
	return _c
}

// ListByFollower provides a mock function with given fields: ctx, userID, from
func (_m *MockConcertUseCase) ListByFollower(ctx context.Context, userID string, from *time.Time) ([]*entity.Concert, error) {
	ret := _m.Called(ctx, userID, from)

	if len(ret) == 0 {
		panic("no return value specified for ListByFollower")
	}

	var r0 []*entity.Concert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) ([]*entity.Concert, error)); ok {
		return rf(ctx, userID, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time) []*entity.Concert); ok {
		r0 = rf(ctx, userID, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time) error); ok {
		r1 = rf(ctx, userID, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_ListByFollower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByFollower'
type MockConcertUseCase_ListByFollower_Call struct {
	*mock.Call
}

// ListByFollower is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - from *time.Time
func (_e *MockConcertUseCase_Expecter) ListByFollower(ctx interface{}, userID interface{}, from interface{}) *MockConcertUseCase_ListByFollower_Call {
	return &MockConcertUseCase_ListByFollower_Call{Call: _e.mock.On("ListByFollower", ctx, userID, from)}
}

func (_c *MockConcertUseCase_ListByFollower_Call) Run(run func(ctx context.Context, userID string, from *time.Time)) *MockConcertUseCase_ListByFollower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockConcertUseCase_ListByFollower_Call) Return(_a0 []*entity.Concert, _a1 error) *MockConcertUseCase_ListByFollower_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_ListByFollower_Call) RunAndReturn(run func(context.Context, string, *time.Time) ([]*entity.Concert, error)) *MockConcertUseCase_ListByFollower_Call {
	_c.Call.Return(run)
	return _c
}

// ListByFollowerGrouped provides a mock function with given fields: ctx, userID, home, from
func (_m *MockConcertUseCase) ListByFollowerGrouped(ctx context.Context, userID string, home *entity.Home, from *time.Time) ([]*entity.ProximityGroup, error) {
	ret := _m.Called(ctx, userID, home, from)

	if len(ret) == 0 {
		panic("no return value specified for ListByFollowerGrouped")
	}

	var r0 []*entity.ProximityGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entity.Home, *time.Time) ([]*entity.ProximityGroup, error)); ok {
		return rf(ctx, userID, home, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *entity.Home, *time.Time) []*entity.ProximityGroup); ok {
		r0 = rf(ctx, userID, home, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProximityGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *entity.Home, *time.Time) error); ok {
		r1 = rf(ctx, userID, home, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_ListByFollowerGrouped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByFollowerGrouped'
type MockConcertUseCase_ListByFollowerGrouped_Call struct {
	*mock.Call
}

// ListByFollowerGrouped is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - home *entity.Home
//   - from *time.Time
func (_e *MockConcertUseCase_Expecter) ListByFollowerGrouped(ctx interface{}, userID interface{}, home interface{}, from interface{}) *MockConcertUseCase_ListByFollowerGrouped_Call {
	return &MockConcertUseCase_ListByFollowerGrouped_Call{Call: _e.mock.On("ListByFollowerGrouped", ctx, userID, home, from)}
}

func (_c *MockConcertUseCase_ListByFollowerGrouped_Call) Run(run func(ctx context.Context, userID string, home *entity.Home, from *time.Time)) *MockConcertUseCase_ListByFollowerGrouped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entity.Home), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockConcertUseCase_ListByFollowerGrouped_Call) Return(_a0 []*entity.ProximityGroup, _a1 error) *MockConcertUseCase_ListByFollowerGrouped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_ListByFollowerGrouped_Call) RunAndReturn(run func(context.Context, string, *entity.Home, *time.Time) ([]*entity.ProximityGroup, error)) *MockConcertUseCase_ListByFollowerGrouped_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLocation provides a mock function with given fields: ctx, location, from, to
func (_m *MockConcertUseCase) ListByLocation(ctx context.Context, location *entity.GeoLocation, from time.Time, to time.Time) ([]*entity.ProximityGroup, error) {
	ret := _m.Called(ctx, location, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListByLocation")
	}

	var r0 []*entity.ProximityGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GeoLocation, time.Time, time.Time) ([]*entity.ProximityGroup, error)); ok {
		return rf(ctx, location, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GeoLocation, time.Time, time.Time) []*entity.ProximityGroup); ok {
		r0 = rf(ctx, location, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProximityGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.GeoLocation, time.Time, time.Time) error); ok {
		r1 = rf(ctx, location, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_ListByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLocation'
type MockConcertUseCase_ListByLocation_Call struct {
	*mock.Call
}

// ListByLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - location *entity.GeoLocation
//   - from time.Time
//   - to time.Time
func (_e *MockConcertUseCase_Expecter) ListByLocation(ctx interface{}, location interface{}, from interface{}, to interface{}) *MockConcertUseCase_ListByLocation_Call {
	return &MockConcertUseCase_ListByLocation_Call{Call: _e.mock.On("ListByLocation", ctx, location, from, to)}
}

func (_c *MockConcertUseCase_ListByLocation_Call) Run(run func(ctx context.Context, location *entity.GeoLocation, from time.Time, to time.Time)) *MockConcertUseCase_ListByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.GeoLocation), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockConcertUseCase_ListByLocation_Call) Return(_a0 []*entity.ProximityGroup, _a1 error) *MockConcertUseCase_ListByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_ListByLocation_Call) RunAndReturn(run func(context.Context, *entity.GeoLocation, time.Time, time.Time) ([]*entity.ProximityGroup, error)) *MockConcertUseCase_ListByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// SearchNewConcerts provides a mock function with given fields: ctx, artistID
func (_m *MockConcertUseCase) SearchNewConcerts(ctx context.Context, artistID string) ([]*entity.Concert, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for SearchNewConcerts")
	}

	var r0 []*entity.Concert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Concert, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Concert); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Concert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConcertUseCase_SearchNewConcerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchNewConcerts'
type MockConcertUseCase_SearchNewConcerts_Call struct {
	*mock.Call
}

// SearchNewConcerts is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID string
func (_e *MockConcertUseCase_Expecter) SearchNewConcerts(ctx interface{}, artistID interface{}) *MockConcertUseCase_SearchNewConcerts_Call {
	return &MockConcertUseCase_SearchNewConcerts_Call{Call: _e.mock.On("SearchNewConcerts", ctx, artistID)}
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) Run(run func(ctx context.Context, artistID string)) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) Return(_a0 []*entity.Concert, _a1 error) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConcertUseCase_SearchNewConcerts_Call) RunAndReturn(run func(context.Context, string) ([]*entity.Concert, error)) *MockConcertUseCase_SearchNewConcerts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConcertUseCase creates a new instance of MockConcertUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcertUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcertUseCase {
	mock := &MockConcertUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
