// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockImageStorer is an autogenerated mock type for the ImageStorer type
type MockImageStorer struct {
	mock.Mock
}

type MockImageStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageStorer) EXPECT() *MockImageStorer_Expecter {
	return &MockImageStorer_Expecter{mock: &_m.Mock}
}

// Put provides a mock function with given fields: ctx, bucket, key, contentType, data
func (_m *MockImageStorer) Put(ctx context.Context, bucket string, key string, contentType string, data []byte) error {
	ret := _m.Called(ctx, bucket, key, contentType, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) error); ok {
		r0 = rf(ctx, bucket, key, contentType, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorer_Put_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - contentType string
//   - data []byte
func (_e *MockImageStorer_Expecter) Put(ctx interface{}, bucket interface{}, key interface{}, contentType interface{}, data interface{}) *MockImageStorer_Put_Call {
	return &MockImageStorer_Put_Call{Call: _e.mock.On("Put", ctx, bucket, key, contentType, data)}
}

func (_c *MockImageStorer_Put_Call) Run(run func(ctx context.Context, bucket string, key string, contentType string, data []byte)) *MockImageStorer_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]byte))
	})
	return _c
}

func (_c *MockImageStorer_Put_Call) Return(_a0 error) *MockImageStorer_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStorer_Put_Call) RunAndReturn(run func(context.Context, string, string, string, []byte) error) *MockImageStorer_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, bucket, key
func (_m *MockImageStorer) Delete(ctx context.Context, bucket string, key string) error {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageStorer_Delete_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockImageStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockImageStorer_Expecter) Delete(ctx interface{}, bucket interface{}, key interface{}) *MockImageStorer_Delete_Call {
	return &MockImageStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, bucket, key)}
}

func (_c *MockImageStorer_Delete_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockImageStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockImageStorer_Delete_Call) Return(_a0 error) *MockImageStorer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStorer_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockImageStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageStorer creates a new instance of MockImageStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageStorer {
	mock := &MockImageStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
